const IDIOMS = [
  { full: "畫蛇添足", blank: "畫＿添足", answer: "蛇", hint: "一種爬行動物", meaning: "比喻多此一舉，反而壞事。", level: "簡單", category: "動物成語", zhuyin: "ㄏㄨㄚˋ ㄕㄜˊ ㄊㄧㄢ ㄗㄨˊ", example: "這件事可以用「畫蛇添足」來形容。" },
  { full: "亡羊補牢", blank: "亡羊補＿", answer: "牢", hint: "關牲畜的地方", meaning: "比喻出了問題後及時補救，還不算晚。", level: "簡單", category: "生活常用", zhuyin: "ㄨㄤˊ ㄧㄤˊ ㄅㄨˇ ㄌㄠˊ", example: "這件事可以用「亡羊補牢」來形容。" },
  { full: "井底之蛙", blank: "井底之＿", answer: "蛙", hint: "住在水邊的動物", meaning: "比喻見識狹小的人。", level: "簡單", category: "動物成語", zhuyin: "ㄐㄧㄥˇ ㄉㄧˇ ㄓ ㄨㄚ", example: "這件事可以用「井底之蛙」來形容。" },
  { full: "守株待兔", blank: "守株待＿", answer: "兔", hint: "一種耳朵很長的動物", meaning: "比喻不努力，只想靠僥倖成功。", level: "簡單", category: "動物成語", zhuyin: "ㄕㄡˇ ㄓㄨ ㄉㄞˋ ㄊㄨˋ", example: "這件事可以用「守株待兔」來形容。" },
  { full: "杯弓蛇影", blank: "杯弓蛇＿", answer: "影", hint: "光照後產生的形狀", meaning: "比喻疑神疑鬼，自相驚擾。", level: "中等", category: "動物成語", zhuyin: "ㄅㄟ ㄍㄨㄥ ㄕㄜˊ ㄧㄥˇ", example: "這件事可以用「杯弓蛇影」來形容。" },
  { full: "對牛彈琴", blank: "對牛彈＿", answer: "琴", hint: "一種樂器", meaning: "比喻對不懂道理的人講道理。", level: "簡單", category: "動物成語", zhuyin: "ㄉㄨㄟˋ ㄋㄧㄡˊ ㄊㄢˊ ㄑㄧㄣˊ", example: "這件事可以用「對牛彈琴」來形容。" },
  { full: "狐假虎威", blank: "狐假虎＿", answer: "威", hint: "威風、氣勢", meaning: "比喻仗著別人的勢力欺壓人。", level: "簡單", category: "動物成語", zhuyin: "ㄏㄨˊ ㄐㄧㄚˇ ㄏㄨˇ ㄨㄟ", example: "這件事可以用「狐假虎威」來形容。" },
  { full: "龍飛鳳舞", blank: "龍飛鳳＿", answer: "舞", hint: "跳動的動作", meaning: "形容字體活潑有氣勢。", level: "中等", category: "動物成語", zhuyin: "ㄌㄨㄥˊ ㄈㄟ ㄈㄥˋ ㄨˇ", example: "這件事可以用「龍飛鳳舞」來形容。" },
  { full: "一石二鳥", blank: "一石二＿", answer: "鳥", hint: "會飛的動物", meaning: "比喻做一件事得到兩種好處。", level: "簡單", category: "數字成語", zhuyin: "ㄧˋ ㄕˊ ㄦˋ ㄋㄧㄠˇ", example: "這件事可以用「一石二鳥」來形容。" },
  { full: "九牛一毛", blank: "九牛一＿", answer: "毛", hint: "動物身上的細毛", meaning: "比喻極大數量中的一小部分。", level: "簡單", category: "數字成語", zhuyin: "ㄐㄧㄡˇ ㄋㄧㄡˊ ㄧˋ ㄇㄠˊ", example: "這件事可以用「九牛一毛」來形容。" },
  { full: "三心二意", blank: "三心二＿", answer: "意", hint: "想法、心意", meaning: "形容心思不專一。", level: "簡單", category: "數字成語", zhuyin: "ㄙㄢ ㄒㄧㄣ ㄦˋ ㄧˋ", example: "這件事可以用「三心二意」來形容。" },
  { full: "四面楚歌", blank: "四面楚＿", answer: "歌", hint: "唱出來的聲音", meaning: "比喻陷入孤立危急的困境。", level: "中等", category: "歷史故事", zhuyin: "ㄙˋ ㄇㄧㄢˋ ㄔㄨˇ ㄍㄜ", example: "這件事可以用「四面楚歌」來形容。" },
  { full: "五花八門", blank: "五花八＿", answer: "門", hint: "入口，也可指種類", meaning: "形容種類繁多、變化很多。", level: "簡單", category: "數字成語", zhuyin: "ㄨˇ ㄏㄨㄚ ㄅㄚ ㄇㄣˊ", example: "這件事可以用「五花八門」來形容。" },
  { full: "六神無主", blank: "六神無＿", answer: "主", hint: "主人、主張", meaning: "形容驚慌失措，沒有主意。", level: "簡單", category: "數字成語", zhuyin: "ㄌㄧㄡˋ ㄕㄣˊ ㄨˊ ㄓㄨˇ", example: "這件事可以用「六神無主」來形容。" },
  { full: "七上八下", blank: "七上八＿", answer: "下", hint: "上的相反", meaning: "形容心中不安。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧ ㄕㄤˋ ㄅㄚ ㄒㄧㄚˋ", example: "這件事可以用「七上八下」來形容。" },
  { full: "八面玲瓏", blank: "八面玲＿", answer: "瓏", hint: "精巧通透", meaning: "形容人處事圓滑，面面俱到。", level: "中等", category: "數字成語", zhuyin: "ㄅㄚ ㄇㄧㄢˋ ㄌㄧㄥˊ ㄌㄨㄥˊ", example: "這件事可以用「八面玲瓏」來形容。" },
  { full: "十全十美", blank: "十全十＿", answer: "美", hint: "漂亮、完好", meaning: "形容非常完美，毫無缺點。", level: "簡單", category: "數字成語", zhuyin: "ㄕˊ ㄑㄩㄢˊ ㄕˊ ㄇㄟˇ", example: "這件事可以用「十全十美」來形容。" },
  { full: "一帆風順", blank: "一帆風＿", answer: "順", hint: "不逆、不阻礙", meaning: "比喻事情進行順利。", level: "簡單", category: "生活常用", zhuyin: "ㄧˋ ㄈㄢˊ ㄈㄥ ㄕㄨㄣˋ", example: "這件事可以用「一帆風順」來形容。" },
  { full: "一鳴驚人", blank: "一鳴驚＿", answer: "人", hint: "人類", meaning: "比喻平時默默無聞，一表現就令人驚訝。", level: "中等", category: "生活常用", zhuyin: "ㄧˋ ㄇㄧㄥˊ ㄐㄧㄥ ㄖㄣˊ", example: "這件事可以用「一鳴驚人」來形容。" },
  { full: "一目了然", blank: "一目了＿", answer: "然", hint: "清楚的樣子", meaning: "一看就很清楚。", level: "中等", category: "生活常用", zhuyin: "ㄧˊ ㄇㄨˋ ㄌㄧㄠˇ ㄖㄢˊ", example: "這件事可以用「一目了然」來形容。" },
  { full: "水落石出", blank: "水落石＿", answer: "出", hint: "出現", meaning: "比喻事情真相大白。", level: "簡單", category: "自然成語", zhuyin: "ㄕㄨㄟˇ ㄌㄨㄛˋ ㄕˊ ㄔㄨ", example: "這件事可以用「水落石出」來形容。" },
  { full: "風和日麗", blank: "風和日＿", answer: "麗", hint: "美麗", meaning: "形容天氣晴朗和暖。", level: "簡單", category: "自然成語", zhuyin: "ㄈㄥ ㄏㄜˊ ㄖˋ ㄌㄧˋ", example: "這件事可以用「風和日麗」來形容。" },
  { full: "山明水秀", blank: "山明水＿", answer: "秀", hint: "秀麗", meaning: "形容山水風景優美。", level: "簡單", category: "自然成語", zhuyin: "ㄕㄢ ㄇㄧㄥˊ ㄕㄨㄟˇ ㄒㄧㄡˋ", example: "這件事可以用「山明水秀」來形容。" },
  { full: "雨過天青", blank: "雨過天＿", answer: "青", hint: "天空的顏色", meaning: "比喻情況由壞轉好。", level: "中等", category: "自然成語", zhuyin: "ㄩˇ ㄍㄨㄛˋ ㄊㄧㄢ ㄑㄧㄥ", example: "這件事可以用「雨過天青」來形容。" },
  { full: "草木皆兵", blank: "草木皆＿", answer: "兵", hint: "士兵", meaning: "形容驚恐疑懼，把草木都當成敵兵。", level: "中等", category: "歷史故事", zhuyin: "ㄘㄠˇ ㄇㄨˋ ㄐㄧㄝ ㄅㄧㄥ", example: "這件事可以用「草木皆兵」來形容。" },
  { full: "破釜沉舟", blank: "破釜沉＿", answer: "舟", hint: "船", meaning: "比喻下定決心，不留退路。", level: "中等", category: "歷史故事", zhuyin: "ㄆㄛˋ ㄈㄨˇ ㄔㄣˊ ㄓㄡ", example: "這件事可以用「破釜沉舟」來形容。" },
  { full: "指鹿為馬", blank: "指鹿為＿", answer: "馬", hint: "一種動物", meaning: "比喻故意顛倒黑白。", level: "中等", category: "歷史故事", zhuyin: "ㄓˇ ㄌㄨˋ ㄨㄟˊ ㄇㄚˇ", example: "這件事可以用「指鹿為馬」來形容。" },
  { full: "臥薪嘗膽", blank: "臥薪嘗＿", answer: "膽", hint: "苦膽", meaning: "形容刻苦自勵，發憤圖強。", level: "中等", category: "歷史故事", zhuyin: "ㄨㄛˋ ㄒㄧㄣ ㄔㄤˊ ㄉㄢˇ", example: "這件事可以用「臥薪嘗膽」來形容。" },
  { full: "紙上談兵", blank: "紙上談＿", answer: "兵", hint: "軍事、士兵", meaning: "比喻只會空談理論，不能解決實際問題。", level: "中等", category: "歷史故事", zhuyin: "ㄓˇ ㄕㄤˋ ㄊㄢˊ ㄅㄧㄥ", example: "這件事可以用「紙上談兵」來形容。" },
  { full: "完璧歸趙", blank: "完璧歸＿", answer: "趙", hint: "戰國時代的國名", meaning: "比喻把原物完整歸還。", level: "困難", category: "歷史故事", zhuyin: "ㄨㄢˊ ㄅㄧˋ ㄍㄨㄟ ㄓㄠˋ", example: "這件事可以用「完璧歸趙」來形容。" },
  { full: "班門弄斧", blank: "班門弄＿", answer: "斧", hint: "砍木頭的工具", meaning: "比喻在行家面前賣弄本領。", level: "中等", category: "生活常用", zhuyin: "ㄅㄢ ㄇㄣˊ ㄋㄨㄥˋ ㄈㄨˇ", example: "這件事可以用「班門弄斧」來形容。" },
  { full: "胸有成竹", blank: "胸有成＿", answer: "竹", hint: "一種植物", meaning: "比喻做事之前已有完整計畫。", level: "中等", category: "生活常用", zhuyin: "ㄒㄩㄥ ㄧㄡˇ ㄔㄥˊ ㄓㄨˊ", example: "這件事可以用「胸有成竹」來形容。" },
  { full: "雪中送炭", blank: "雪中送＿", answer: "炭", hint: "可燃燒取暖", meaning: "比喻在別人急需時給予幫助。", level: "簡單", category: "生活常用", zhuyin: "ㄒㄩㄝˇ ㄓㄨㄥ ㄙㄨㄥˋ ㄊㄢˋ", example: "這件事可以用「雪中送炭」來形容。" },
  { full: "錦上添花", blank: "錦上添＿", answer: "花", hint: "植物開出的美麗部分", meaning: "比喻美好的事物更加美好。", level: "簡單", category: "生活常用", zhuyin: "ㄐㄧㄣˇ ㄕㄤˋ ㄊㄧㄢ ㄏㄨㄚ", example: "這件事可以用「錦上添花」來形容。" },
  { full: "半途而廢", blank: "半途而＿", answer: "廢", hint: "停止、放棄", meaning: "事情做到一半就停止。", level: "簡單", category: "生活常用", zhuyin: "ㄅㄢˋ ㄊㄨˊ ㄦˊ ㄈㄟˋ", example: "這件事可以用「半途而廢」來形容。" },
  { full: "自相矛盾", blank: "自相矛＿", answer: "盾", hint: "古代防禦武器", meaning: "比喻言行前後互相牴觸。", level: "中等", category: "故事寓言", zhuyin: "ㄗˋ ㄒㄧㄤ ㄇㄠˊ ㄉㄨㄣˋ", example: "這件事可以用「自相矛盾」來形容。" },
  { full: "刻舟求劍", blank: "刻舟求＿", answer: "劍", hint: "古代兵器", meaning: "比喻拘泥成法，不知變通。", level: "中等", category: "故事寓言", zhuyin: "ㄎㄜˋ ㄓㄡ ㄑㄧㄡˊ ㄐㄧㄢˋ", example: "這件事可以用「刻舟求劍」來形容。" },
  { full: "拔苗助長", blank: "拔苗助＿", answer: "長", hint: "成長", meaning: "比喻違反事物規律，急於求成反而壞事。", level: "中等", category: "故事寓言", zhuyin: "ㄅㄚˊ ㄇㄧㄠˊ ㄓㄨˋ ㄓㄤˇ", example: "這件事可以用「拔苗助長」來形容。" },
  { full: "掩耳盜鈴", blank: "掩耳盜＿", answer: "鈴", hint: "會發出聲音的小物", meaning: "比喻自欺欺人。", level: "簡單", category: "故事寓言", zhuyin: "ㄧㄢˇ ㄦˇ ㄉㄠˋ ㄌㄧㄥˊ", example: "這件事可以用「掩耳盜鈴」來形容。" },
  { full: "濫竽充數", blank: "濫竽充＿", answer: "數", hint: "數目", meaning: "比喻沒有真才實學的人混在其中。", level: "中等", category: "故事寓言", zhuyin: "ㄌㄢˋ ㄩˊ ㄔㄨㄥ ㄕㄨˋ", example: "這件事可以用「濫竽充數」來形容。" },
  { full: "愚公移山", blank: "愚公移＿", answer: "山", hint: "很高的地形", meaning: "比喻有毅力，不怕困難。", level: "簡單", category: "故事寓言", zhuyin: "ㄩˊ ㄍㄨㄥ ㄧˊ ㄕㄢ", example: "這件事可以用「愚公移山」來形容。" },
  { full: "買櫝還珠", blank: "買櫝還＿", answer: "珠", hint: "珍珠", meaning: "比喻取捨不當，重視次要而忽略主要。", level: "困難", category: "故事寓言", zhuyin: "ㄇㄞˇ ㄉㄨˊ ㄏㄨㄢˊ ㄓㄨ", example: "這件事可以用「買櫝還珠」來形容。" },
  { full: "黔驢技窮", blank: "黔驢技＿", answer: "窮", hint: "用盡、沒有了", meaning: "比喻有限的本領已經用盡。", level: "困難", category: "故事寓言", zhuyin: "ㄑㄧㄢˊ ㄌㄩˊ ㄐㄧˋ ㄑㄩㄥˊ", example: "這件事可以用「黔驢技窮」來形容。" },
  { full: "鷸蚌相爭", blank: "鷸蚌相＿", answer: "爭", hint: "爭鬥", meaning: "比喻雙方相持不下，讓第三者得利。", level: "困難", category: "故事寓言", zhuyin: "ㄩˋ ㄅㄤˋ ㄒㄧㄤ ㄓㄥ", example: "這件事可以用「鷸蚌相爭」來形容。" },
  { full: "得意忘形", blank: "得意忘＿", answer: "形", hint: "外表、形態", meaning: "形容高興得失去常態。", level: "簡單", category: "生活常用", zhuyin: "ㄉㄜˊ ㄧˋ ㄨㄤˋ ㄒㄧㄥˊ", example: "這件事可以用「得意忘形」來形容。" },
  { full: "心曠神怡", blank: "心曠神＿", answer: "怡", hint: "愉快", meaning: "心情開朗，精神愉快。", level: "中等", category: "生活常用", zhuyin: "ㄒㄧㄣ ㄎㄨㄤˋ ㄕㄣˊ ㄧˊ", example: "這件事可以用「心曠神怡」來形容。" },
  { full: "目瞪口呆", blank: "目瞪口＿", answer: "呆", hint: "發愣", meaning: "形容驚訝得說不出話來。", level: "簡單", category: "生活常用", zhuyin: "ㄇㄨˋ ㄉㄥˋ ㄎㄡˇ ㄉㄞ", example: "這件事可以用「目瞪口呆」來形容。" },
  { full: "口是心非", blank: "口是心＿", answer: "非", hint: "不是", meaning: "嘴上說是，心裡卻不是。", level: "簡單", category: "生活常用", zhuyin: "ㄎㄡˇ ㄕˋ ㄒㄧㄣ ㄈㄟ", example: "這件事可以用「口是心非」來形容。" },
  { full: "喜出望外", blank: "喜出望＿", answer: "外", hint: "外面", meaning: "因意外的好事而非常高興。", level: "中等", category: "生活常用", zhuyin: "ㄒㄧˇ ㄔㄨ ㄨㄤˋ ㄨㄞˋ", example: "這件事可以用「喜出望外」來形容。" },
  { full: "迫不及待", blank: "迫不及＿", answer: "待", hint: "等待", meaning: "急迫得不能再等待。", level: "簡單", category: "生活常用", zhuyin: "ㄆㄛˋ ㄅㄨˋ ㄐㄧˊ ㄉㄞˋ", example: "這件事可以用「迫不及待」來形容。" },
  { full: "望梅止渴", blank: "望梅止＿", answer: "渴", hint: "口很乾", meaning: "比喻用空想安慰自己。", level: "中等", category: "歷史故事", zhuyin: "ㄨㄤˋ ㄇㄟˊ ㄓˇ ㄎㄜˇ", example: "這件事可以用「望梅止渴」來形容。" },
  { full: "東施效顰", blank: "東施效＿", answer: "顰", hint: "皺眉", meaning: "比喻盲目模仿，效果反而不好。", level: "困難", category: "歷史故事", zhuyin: "ㄉㄨㄥ ㄕ ㄒㄧㄠˋ ㄆㄧㄣˊ", example: "這件事可以用「東施效顰」來形容。" },
  { full: "負荊請罪", blank: "負荊請＿", answer: "罪", hint: "承認錯誤", meaning: "表示主動向人認錯賠罪。", level: "中等", category: "歷史故事", zhuyin: "ㄈㄨˋ ㄐㄧㄥ ㄑㄧㄥˇ ㄗㄨㄟˋ", example: "這件事可以用「負荊請罪」來形容。" },
  { full: "毛遂自薦", blank: "毛遂自＿", answer: "薦", hint: "推薦", meaning: "比喻自告奮勇推薦自己。", level: "中等", category: "歷史故事", zhuyin: "ㄇㄠˊ ㄙㄨㄟˋ ㄗˋ ㄐㄧㄢˋ", example: "這件事可以用「毛遂自薦」來形容。" },
  { full: "夜郎自大", blank: "夜郎自＿", answer: "大", hint: "大小的大", meaning: "比喻人見識短淺而自以為了不起。", level: "中等", category: "歷史故事", zhuyin: "ㄧㄝˋ ㄌㄤˊ ㄗˋ ㄉㄚˋ", example: "這件事可以用「夜郎自大」來形容。" },
  { full: "邯鄲學步", blank: "邯鄲學＿", answer: "步", hint: "走路的動作", meaning: "比喻模仿別人不成，反而失去原有本領。", level: "困難", category: "歷史故事", zhuyin: "ㄏㄢˊ ㄉㄢ ㄒㄩㄝˊ ㄅㄨˋ", example: "這件事可以用「邯鄲學步」來形容。" },
  { full: "精衛填海", blank: "精衛填＿", answer: "海", hint: "大片海水", meaning: "比喻意志堅定，不怕困難。", level: "中等", category: "故事寓言", zhuyin: "ㄐㄧㄥ ㄨㄟˋ ㄊㄧㄢˊ ㄏㄞˇ", example: "這件事可以用「精衛填海」來形容。" },
  { full: "夸父逐日", blank: "夸父逐＿", answer: "日", hint: "太陽", meaning: "比喻有宏大的志向，也可指不自量力。", level: "困難", category: "故事寓言", zhuyin: "ㄎㄨㄚ ㄈㄨˋ ㄓㄨˊ ㄖˋ", example: "這件事可以用「夸父逐日」來形容。" },
  { full: "開卷有益", blank: "開卷有＿", answer: "益", hint: "好處", meaning: "讀書總會有好處。", level: "簡單", category: "學習成語", zhuyin: "ㄎㄞ ㄐㄩㄢˋ ㄧㄡˇ ㄧˋ", example: "這件事可以用「開卷有益」來形容。" },
  { full: "學以致用", blank: "學以致＿", answer: "用", hint: "使用", meaning: "把學到的知識運用到實際中。", level: "簡單", category: "學習成語", zhuyin: "ㄒㄩㄝˊ ㄧˇ ㄓˋ ㄩㄥˋ", example: "這件事可以用「學以致用」來形容。" },
  { full: "溫故知新", blank: "溫故知＿", answer: "新", hint: "新的知識", meaning: "複習舊知識而獲得新體會。", level: "簡單", category: "學習成語", zhuyin: "ㄨㄣ ㄍㄨˋ ㄓ ㄒㄧㄣ", example: "這件事可以用「溫故知新」來形容。" },
  { full: "舉一反三", blank: "舉一反＿", answer: "三", hint: "數字", meaning: "從一件事類推而知道其他事情。", level: "中等", category: "學習成語", zhuyin: "ㄐㄩˇ ㄧ ㄈㄢˇ ㄙㄢ", example: "這件事可以用「舉一反三」來形容。" },
  { full: "融會貫通", blank: "融會貫＿", answer: "通", hint: "通達", meaning: "把各方面知識充分理解並連貫起來。", level: "中等", category: "學習成語", zhuyin: "ㄖㄨㄥˊ ㄏㄨㄟˋ ㄍㄨㄢˋ ㄊㄨㄥ", example: "這件事可以用「融會貫通」來形容。" },
  { full: "孜孜不倦", blank: "孜孜不＿", answer: "倦", hint: "疲倦", meaning: "勤奮努力，不知疲倦。", level: "中等", category: "學習成語", zhuyin: "ㄗ ㄗ ㄅㄨˋ ㄐㄩㄢˋ", example: "這件事可以用「孜孜不倦」來形容。" },
  { full: "博學多聞", blank: "博學多＿", answer: "聞", hint: "聽聞、見聞", meaning: "學問廣博，見聞豐富。", level: "中等", category: "學習成語", zhuyin: "ㄅㄛˊ ㄒㄩㄝˊ ㄉㄨㄛ ㄨㄣˊ", example: "這件事可以用「博學多聞」來形容。" },
  { full: "專心致志", blank: "專心致＿", answer: "志", hint: "心志", meaning: "形容一心一意，集中精神。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨㄢ ㄒㄧㄣ ㄓˋ ㄓˋ", example: "這件事可以用「專心致志」來形容。" },
  { full: "粗心大意", blank: "粗心大＿", answer: "意", hint: "心意", meaning: "做事不仔細。", level: "簡單", category: "生活常用", zhuyin: "ㄘㄨ ㄒㄧㄣ ㄉㄚˋ ㄧˋ", example: "這件事可以用「粗心大意」來形容。" },
  { full: "小心翼翼", blank: "小心翼＿", answer: "翼", hint: "重複字", meaning: "形容非常謹慎小心。", level: "簡單", category: "生活常用", zhuyin: "ㄒㄧㄠˇ ㄒㄧㄣ ㄧˋ ㄧˋ", example: "這件事可以用「小心翼翼」來形容。" },
  { full: "大驚小怪", blank: "大驚小＿", answer: "怪", hint: "奇怪", meaning: "形容對不足為奇的事過分驚訝。", level: "簡單", category: "生活常用", zhuyin: "ㄉㄚˋ ㄐㄧㄥ ㄒㄧㄠˇ ㄍㄨㄞˋ", example: "這件事可以用「大驚小怪」來形容。" },
  { full: "千辛萬苦", blank: "千辛萬＿", answer: "苦", hint: "辛苦", meaning: "形容非常多的艱難困苦。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧㄢ ㄒㄧㄣ ㄨㄢˋ ㄎㄨˇ", example: "這件事可以用「千辛萬苦」來形容。" },
  { full: "千變萬化", blank: "千變萬＿", answer: "化", hint: "變化", meaning: "形容變化非常多。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧㄢ ㄅㄧㄢˋ ㄨㄢˋ ㄏㄨㄚˋ", example: "這件事可以用「千變萬化」來形容。" },
  { full: "千鈞一髮", blank: "千鈞一＿", answer: "髮", hint: "頭上的細絲", meaning: "比喻情況非常危急。", level: "中等", category: "數字成語", zhuyin: "ㄑㄧㄢ ㄐㄩㄣ ㄧˊ ㄈㄚˇ", example: "這件事可以用「千鈞一髮」來形容。" },
  { full: "萬眾一心", blank: "萬眾一＿", answer: "心", hint: "心意", meaning: "大家團結一致。", level: "簡單", category: "數字成語", zhuyin: "ㄨㄢˋ ㄓㄨㄥˋ ㄧˋ ㄒㄧㄣ", example: "這件事可以用「萬眾一心」來形容。" },
  { full: "百發百中", blank: "百發百＿", answer: "中", hint: "射中", meaning: "形容射擊或預測非常準確。", level: "簡單", category: "數字成語", zhuyin: "ㄅㄞˇ ㄈㄚ ㄅㄞˇ ㄓㄨㄥˋ", example: "這件事可以用「百發百中」來形容。" },
  { full: "百折不撓", blank: "百折不＿", answer: "撓", hint: "屈服、動搖", meaning: "比喻意志堅強，屢受挫折也不退縮。", level: "困難", category: "數字成語", zhuyin: "ㄅㄞˇ ㄓㄜˊ ㄅㄨˋ ㄋㄠˊ", example: "這件事可以用「百折不撓」來形容。" },
  { full: "前功盡棄", blank: "前功盡＿", answer: "棄", hint: "放棄", meaning: "以前的努力全部白費。", level: "中等", category: "生活常用", zhuyin: "ㄑㄧㄢˊ ㄍㄨㄥ ㄐㄧㄣˋ ㄑㄧˋ", example: "這件事可以用「前功盡棄」來形容。" },
  { full: "後來居上", blank: "後來居＿", answer: "上", hint: "下的相反", meaning: "後來的人或事物超過先前的。", level: "簡單", category: "生活常用", zhuyin: "ㄏㄡˋ ㄌㄞˊ ㄐㄩ ㄕㄤˋ", example: "這件事可以用「後來居上」來形容。" },
  { full: "左顧右盼", blank: "左顧右＿", answer: "盼", hint: "看", meaning: "向左右兩邊看，也形容猶豫不決。", level: "簡單", category: "生活常用", zhuyin: "ㄗㄨㄛˇ ㄍㄨˋ ㄧㄡˋ ㄆㄢˋ", example: "這件事可以用「左顧右盼」來形容。" },
  { full: "南轅北轍", blank: "南轅北＿", answer: "轍", hint: "車輪壓過的痕跡", meaning: "比喻行動和目的相反。", level: "困難", category: "故事寓言", zhuyin: "ㄋㄢˊ ㄩㄢˊ ㄅㄟˇ ㄔㄜˋ", example: "這件事可以用「南轅北轍」來形容。" },
  { full: "東張西望", blank: "東張西＿", answer: "望", hint: "看", meaning: "到處看。", level: "簡單", category: "生活常用", zhuyin: "ㄉㄨㄥ ㄓㄤ ㄒㄧ ㄨㄤˋ", example: "這件事可以用「東張西望」來形容。" },
  { full: "上行下效", blank: "上行下＿", answer: "效", hint: "模仿", meaning: "上面的人怎麼做，下面的人就跟著做。", level: "中等", category: "生活常用", zhuyin: "ㄕㄤˋ ㄒㄧㄥˊ ㄒㄧㄚˋ ㄒㄧㄠˋ", example: "這件事可以用「上行下效」來形容。" },
  { full: "天衣無縫", blank: "天衣無＿", answer: "縫", hint: "衣服接合的線", meaning: "比喻事物周密完美，找不出破綻。", level: "中等", category: "生活常用", zhuyin: "ㄊㄧㄢ ㄧ ㄨˊ ㄈㄥˋ", example: "這件事可以用「天衣無縫」來形容。" },
  { full: "海闊天空", blank: "海闊天＿", answer: "空", hint: "天空", meaning: "形容胸襟開闊或言談漫無邊際。", level: "簡單", category: "自然成語", zhuyin: "ㄏㄞˇ ㄎㄨㄛˋ ㄊㄧㄢ ㄎㄨㄥ", example: "這件事可以用「海闊天空」來形容。" },
  { full: "柳暗花明", blank: "柳暗花＿", answer: "明", hint: "明亮", meaning: "比喻在困境中出現轉機。", level: "中等", category: "自然成語", zhuyin: "ㄌㄧㄡˇ ㄢˋ ㄏㄨㄚ ㄇㄧㄥˊ", example: "這件事可以用「柳暗花明」來形容。" },
  { full: "春暖花開", blank: "春暖花＿", answer: "開", hint: "花朵綻放", meaning: "形容春天景色美好，也比喻好時機到來。", level: "簡單", category: "自然成語", zhuyin: "ㄔㄨㄣ ㄋㄨㄢˇ ㄏㄨㄚ ㄎㄞ", example: "這件事可以用「春暖花開」來形容。" },
  { full: "鳥語花香", blank: "鳥語花＿", answer: "香", hint: "香味", meaning: "形容春天景色優美。", level: "簡單", category: "自然成語", zhuyin: "ㄋㄧㄠˇ ㄩˇ ㄏㄨㄚ ㄒㄧㄤ", example: "這件事可以用「鳥語花香」來形容。" },
  { full: "電光石火", blank: "電光石＿", answer: "火", hint: "燃燒的光", meaning: "形容速度極快。", level: "中等", category: "自然成語", zhuyin: "ㄉㄧㄢˋ ㄍㄨㄤ ㄕˊ ㄏㄨㄛˇ", example: "這件事可以用「電光石火」來形容。" },
  { full: "風平浪靜", blank: "風平浪＿", answer: "靜", hint: "安靜", meaning: "比喻平靜無事。", level: "簡單", category: "自然成語", zhuyin: "ㄈㄥ ㄆㄧㄥˊ ㄌㄤˋ ㄐㄧㄥˋ", example: "這件事可以用「風平浪靜」來形容。" },
  { full: "雲開見日", blank: "雲開見＿", answer: "日", hint: "太陽", meaning: "比喻黑暗過去，光明出現。", level: "中等", category: "自然成語", zhuyin: "ㄩㄣˊ ㄎㄞ ㄐㄧㄢˋ ㄖˋ", example: "這件事可以用「雲開見日」來形容。" },
  { full: "星羅棋布", blank: "星羅棋＿", answer: "布", hint: "分布", meaning: "形容數量很多，分布很廣。", level: "中等", category: "自然成語", zhuyin: "ㄒㄧㄥ ㄌㄨㄛˊ ㄑㄧˊ ㄅㄨˋ", example: "這件事可以用「星羅棋布」來形容。" },
  { full: "聚精會神", blank: "聚精會＿", answer: "神", hint: "精神", meaning: "形容注意力高度集中。", level: "簡單", category: "學習成語", zhuyin: "ㄐㄩˋ ㄐㄧㄥ ㄏㄨㄟˋ ㄕㄣˊ", example: "這件事可以用「聚精會神」來形容。" },
  { full: "聞雞起舞", blank: "聞雞起＿", answer: "舞", hint: "舞動", meaning: "比喻有志者及時奮發努力。", level: "中等", category: "歷史故事", zhuyin: "ㄨㄣˊ ㄐㄧ ㄑㄧˇ ㄨˇ", example: "這件事可以用「聞雞起舞」來形容。" },
  { full: "懸梁刺股", blank: "懸梁刺＿", answer: "股", hint: "大腿", meaning: "形容刻苦讀書。", level: "困難", category: "學習成語", zhuyin: "ㄒㄩㄢˊ ㄌㄧㄤˊ ㄘˋ ㄍㄨˇ", example: "這件事可以用「懸梁刺股」來形容。" },
  { full: "韋編三絕", blank: "韋編三＿", answer: "絕", hint: "斷掉", meaning: "形容讀書勤奮。", level: "困難", category: "學習成語", zhuyin: "ㄨㄟˊ ㄅㄧㄢ ㄙㄢ ㄐㄩㄝˊ", example: "這件事可以用「韋編三絕」來形容。" },
  { full: "不恥下問", blank: "不恥下＿", answer: "問", hint: "請教", meaning: "不以向地位或學問不如自己的人請教為羞恥。", level: "中等", category: "學習成語", zhuyin: "ㄅㄨˋ ㄔˇ ㄒㄧㄚˋ ㄨㄣˋ", example: "這件事可以用「不恥下問」來形容。" },
  { full: "循序漸進", blank: "循序漸＿", answer: "進", hint: "前進", meaning: "按照一定步驟逐漸進步。", level: "中等", category: "學習成語", zhuyin: "ㄒㄩㄣˊ ㄒㄩˋ ㄐㄧㄢˋ ㄐㄧㄣˋ", example: "這件事可以用「循序漸進」來形容。" },
  { full: "熟能生巧", blank: "熟能生＿", answer: "巧", hint: "技巧", meaning: "熟練了就能產生巧妙的方法。", level: "簡單", category: "學習成語", zhuyin: "ㄕㄨˊ ㄋㄥˊ ㄕㄥ ㄑㄧㄠˇ", example: "這件事可以用「熟能生巧」來形容。" },
  { full: "事半功倍", blank: "事半功＿", answer: "倍", hint: "加倍", meaning: "花較少力氣得到較大成效。", level: "中等", category: "學習成語", zhuyin: "ㄕˋ ㄅㄢˋ ㄍㄨㄥ ㄅㄟˋ", example: "這件事可以用「事半功倍」來形容。" },
  { full: "事倍功半", blank: "事倍功＿", answer: "半", hint: "一半", meaning: "花很多力氣卻只得到很少成效。", level: "中等", category: "學習成語", zhuyin: "ㄕˋ ㄅㄟˋ ㄍㄨㄥ ㄅㄢˋ", example: "這件事可以用「事倍功半」來形容。" },
  { full: "推陳出新", blank: "推陳出＿", answer: "新", hint: "新的", meaning: "去除舊的，創造新的。", level: "中等", category: "生活常用", zhuyin: "ㄊㄨㄟ ㄔㄣˊ ㄔㄨ ㄒㄧㄣ", example: "這件事可以用「推陳出新」來形容。" },
  { full: "別出心裁", blank: "別出心＿", answer: "裁", hint: "設計、安排", meaning: "形容想法獨特，與眾不同。", level: "中等", category: "生活常用", zhuyin: "ㄅㄧㄝˊ ㄔㄨ ㄒㄧㄣ ㄘㄞˊ", example: "這件事可以用「別出心裁」來形容。" },
  { full: "妙手回春", blank: "妙手回＿", answer: "春", hint: "春天", meaning: "稱讚醫術高明，能使病人康復。", level: "中等", category: "生活常用", zhuyin: "ㄇㄧㄠˋ ㄕㄡˇ ㄏㄨㄟˊ ㄔㄨㄣ", example: "這件事可以用「妙手回春」來形容。" },
  { full: "起死回生", blank: "起死回＿", answer: "生", hint: "生命", meaning: "形容醫術高明或把危急情況挽回。", level: "中等", category: "生活常用", zhuyin: "ㄑㄧˇ ㄙˇ ㄏㄨㄟˊ ㄕㄥ", example: "這件事可以用「起死回生」來形容。" },
  { full: "人山人海", blank: "人山＿海", answer: "人", hint: "大量的人群", meaning: "形容人非常多，像山和海一樣。", level: "簡單", category: "生活常用", zhuyin: "ㄖㄣˊ ㄕㄢ ㄖㄣˊ ㄏㄞˇ", example: "這件事可以用「人山人海」來形容。" },
  { full: "車水馬龍", blank: "車水馬＿", answer: "龍", hint: "傳統交通工具旁常見的動物", meaning: "形容車馬往來不絕，非常熱鬧。", level: "中等", category: "生活常用", zhuyin: "ㄔㄜ ㄕㄨㄟˇ ㄇㄚˇ ㄌㄨㄥˊ", example: "這件事可以用「車水馬龍」來形容。" },
  { full: "川流不息", blank: "川流不＿", answer: "息", hint: "停止的相反", meaning: "形容行人、車馬像水流一樣連續不斷。", level: "中等", category: "生活常用", zhuyin: "ㄔㄨㄢ ㄌㄧㄡˊ ㄅㄨˋ ㄒㄧˊ", example: "這件事可以用「川流不息」來形容。" },
  { full: "絡繹不絕", blank: "絡繹不＿", answer: "絕", hint: "斷絕、停止", meaning: "形容人或事物前後相接，連續不斷。", level: "中等", category: "生活常用", zhuyin: "ㄌㄨㄛˋ ㄧˋ ㄅㄨˋ ㄐㄩㄝˊ", example: "這件事可以用「絡繹不絕」來形容。" },
  { full: "門庭若市", blank: "門庭若＿", answer: "市", hint: "市場", meaning: "形容來往的人很多，非常熱鬧。", level: "中等", category: "生活常用", zhuyin: "ㄇㄣˊ ㄊㄧㄥˊ ㄖㄨㄛˋ ㄕˋ", example: "這件事可以用「門庭若市」來形容。" },
  { full: "水泄不通", blank: "水泄不＿", answer: "通", hint: "通過", meaning: "形容擁擠或包圍得非常嚴密。", level: "中等", category: "生活常用", zhuyin: "ㄕㄨㄟˇ ㄒㄧㄝˋ ㄅㄨˋ ㄊㄨㄥ", example: "這件事可以用「水泄不通」來形容。" },
  { full: "摩肩接踵", blank: "摩肩接＿", answer: "踵", hint: "腳後跟", meaning: "形容人多擁擠。", level: "困難", category: "生活常用", zhuyin: "ㄇㄛˊ ㄐㄧㄢ ㄐㄧㄝ ㄓㄨㄥˇ", example: "這件事可以用「摩肩接踵」來形容。" },
  { full: "熙熙攘攘", blank: "熙熙攘＿", answer: "攘", hint: "人群擁擠喧鬧的樣子", meaning: "形容人來人往，非常熱鬧。", level: "困難", category: "生活常用", zhuyin: "ㄒㄧ ㄒㄧ ㄖㄤˇ ㄖㄤˇ", example: "這件事可以用「熙熙攘攘」來形容。" },
  { full: "鴉雀無聲", blank: "鴉雀無＿", answer: "聲", hint: "聲音", meaning: "形容非常安靜，一點聲音也沒有。", level: "簡單", category: "生活常用", zhuyin: "ㄧㄚ ㄑㄩㄝˋ ㄨˊ ㄕㄥ", example: "這件事可以用「鴉雀無聲」來形容。" },
  { full: "萬籟俱寂", blank: "萬籟俱＿", answer: "寂", hint: "安靜", meaning: "形容周圍環境非常安靜。", level: "困難", category: "自然成語", zhuyin: "ㄨㄢˋ ㄌㄞˋ ㄐㄩˋ ㄐㄧˊ", example: "這件事可以用「萬籟俱寂」來形容。" },
  { full: "一塵不染", blank: "一塵不＿", answer: "染", hint: "沾染", meaning: "形容非常乾淨，也比喻品德純潔。", level: "中等", category: "生活常用", zhuyin: "ㄧˋ ㄔㄣˊ ㄅㄨˋ ㄖㄢˇ", example: "這件事可以用「一塵不染」來形容。" },
  { full: "煥然一新", blank: "煥然一＿", answer: "新", hint: "新的", meaning: "形容面貌完全改變，變得很新。", level: "中等", category: "生活常用", zhuyin: "ㄏㄨㄢˋ ㄖㄢˊ ㄧˋ ㄒㄧㄣ", example: "這件事可以用「煥然一新」來形容。" },
  { full: "井井有條", blank: "井井有＿", answer: "條", hint: "條理", meaning: "形容整齊而有條理。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄥˇ ㄐㄧㄥˇ ㄧㄡˇ ㄊㄧㄠˊ", example: "這件事可以用「井井有條」來形容。" },
  { full: "雜亂無章", blank: "雜亂無＿", answer: "章", hint: "章法、條理", meaning: "形容混亂而沒有條理。", level: "中等", category: "生活常用", zhuyin: "ㄗㄚˊ ㄌㄨㄢˋ ㄨˊ ㄓㄤ", example: "這件事可以用「雜亂無章」來形容。" },
  { full: "有條不紊", blank: "有條不＿", answer: "紊", hint: "混亂的相反", meaning: "形容做事有條理，不慌亂。", level: "困難", category: "生活常用", zhuyin: "ㄧㄡˇ ㄊㄧㄠˊ ㄅㄨˋ ㄨㄣˋ", example: "這件事可以用「有條不紊」來形容。" },
  { full: "手忙腳亂", blank: "手忙腳＿", answer: "亂", hint: "混亂", meaning: "形容做事慌張，沒有條理。", level: "簡單", category: "生活常用", zhuyin: "ㄕㄡˇ ㄇㄤˊ ㄐㄧㄠˇ ㄌㄨㄢˋ", example: "這件事可以用「手忙腳亂」來形容。" },
  { full: "驚慌失措", blank: "驚慌失＿", answer: "措", hint: "辦法、安排", meaning: "形容非常害怕，不知道該怎麼辦。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄥ ㄏㄨㄤ ㄕ ㄘㄨㄛˋ", example: "這件事可以用「驚慌失措」來形容。" },
  { full: "鎮定自若", blank: "鎮定自＿", answer: "若", hint: "好像、如同", meaning: "形容遇事沉著，不慌張。", level: "中等", category: "生活常用", zhuyin: "ㄓㄣˋ ㄉㄧㄥˋ ㄗˋ ㄖㄨㄛˋ", example: "這件事可以用「鎮定自若」來形容。" },
  { full: "泰然自若", blank: "泰然自＿", answer: "若", hint: "好像、如同", meaning: "形容態度安然，不慌不忙。", level: "中等", category: "生活常用", zhuyin: "ㄊㄞˋ ㄖㄢˊ ㄗˋ ㄖㄨㄛˋ", example: "這件事可以用「泰然自若」來形容。" },
  { full: "心平氣和", blank: "心平氣＿", answer: "和", hint: "溫和", meaning: "形容心情平靜，態度溫和。", level: "簡單", category: "生活常用", zhuyin: "ㄒㄧㄣ ㄆㄧㄥˊ ㄑㄧˋ ㄏㄜˊ", example: "這件事可以用「心平氣和」來形容。" },
  { full: "怒氣沖天", blank: "怒氣沖＿", answer: "天", hint: "天空", meaning: "形容憤怒到了極點。", level: "簡單", category: "生活常用", zhuyin: "ㄋㄨˋ ㄑㄧˋ ㄔㄨㄥ ㄊㄧㄢ", example: "這件事可以用「怒氣沖天」來形容。" },
  { full: "眉開眼笑", blank: "眉開眼＿", answer: "笑", hint: "笑容", meaning: "形容非常高興的樣子。", level: "簡單", category: "生活常用", zhuyin: "ㄇㄟˊ ㄎㄞ ㄧㄢˇ ㄒㄧㄠˋ", example: "這件事可以用「眉開眼笑」來形容。" },
  { full: "愁眉苦臉", blank: "愁眉苦＿", answer: "臉", hint: "臉部", meaning: "形容憂愁苦悶的樣子。", level: "簡單", category: "生活常用", zhuyin: "ㄔㄡˊ ㄇㄟˊ ㄎㄨˇ ㄌㄧㄢˇ", example: "這件事可以用「愁眉苦臉」來形容。" },
  { full: "垂頭喪氣", blank: "垂頭喪＿", answer: "氣", hint: "精神、氣勢", meaning: "形容失望或沮喪的樣子。", level: "簡單", category: "生活常用", zhuyin: "ㄔㄨㄟˊ ㄊㄡˊ ㄙㄤˋ ㄑㄧˋ", example: "這件事可以用「垂頭喪氣」來形容。" },
  { full: "神采奕奕", blank: "神采奕＿", answer: "奕", hint: "精神飽滿的樣子", meaning: "形容精神飽滿，容光煥發。", level: "中等", category: "生活常用", zhuyin: "ㄕㄣˊ ㄘㄞˇ ㄧˋ ㄧˋ", example: "這件事可以用「神采奕奕」來形容。" },
  { full: "容光煥發", blank: "容光煥＿", answer: "發", hint: "發出、顯現", meaning: "形容精神飽滿，臉色很好。", level: "中等", category: "生活常用", zhuyin: "ㄖㄨㄥˊ ㄍㄨㄤ ㄏㄨㄢˋ ㄈㄚ", example: "這件事可以用「容光煥發」來形容。" },
  { full: "精神抖擻", blank: "精神抖＿", answer: "擻", hint: "振作", meaning: "形容精神振奮。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄥ ㄕㄣˊ ㄉㄡˇ ㄙㄡˇ", example: "這件事可以用「精神抖擻」來形容。" },
  { full: "筋疲力盡", blank: "筋疲力＿", answer: "盡", hint: "用完", meaning: "形容非常疲累，一點力氣也沒有。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄣ ㄆㄧˊ ㄌㄧˋ ㄐㄧㄣˋ", example: "這件事可以用「筋疲力盡」來形容。" },
  { full: "疲憊不堪", blank: "疲憊不＿", answer: "堪", hint: "忍受", meaning: "形容非常疲累。", level: "中等", category: "生活常用", zhuyin: "ㄆㄧˊ ㄅㄟˋ ㄅㄨˋ ㄎㄢ", example: "這件事可以用「疲憊不堪」來形容。" },
  { full: "欣喜若狂", blank: "欣喜若＿", answer: "狂", hint: "發狂", meaning: "形容高興到了極點。", level: "中等", category: "生活常用", zhuyin: "ㄒㄧㄣ ㄒㄧˇ ㄖㄨㄛˋ ㄎㄨㄤˊ", example: "這件事可以用「欣喜若狂」來形容。" },
  { full: "悲痛欲絕", blank: "悲痛欲＿", answer: "絕", hint: "斷絕", meaning: "形容悲傷到了極點。", level: "中等", category: "生活常用", zhuyin: "ㄅㄟ ㄊㄨㄥˋ ㄩˋ ㄐㄩㄝˊ", example: "這件事可以用「悲痛欲絕」來形容。" },
  { full: "大公無私", blank: "大公無＿", answer: "私", hint: "私心", meaning: "形容公正而沒有私心。", level: "簡單", category: "品德修養", zhuyin: "ㄉㄚˋ ㄍㄨㄥ ㄨˊ ㄙ", example: "這件事可以用「大公無私」來形容。" },
  { full: "公正無私", blank: "公正無＿", answer: "私", hint: "私心", meaning: "形容公平正直，沒有偏私。", level: "簡單", category: "品德修養", zhuyin: "ㄍㄨㄥ ㄓㄥˋ ㄨˊ ㄙ", example: "這件事可以用「公正無私」來形容。" },
  { full: "光明磊落", blank: "光明磊＿", answer: "落", hint: "坦蕩、正大", meaning: "形容胸懷坦白，行為正直。", level: "中等", category: "品德修養", zhuyin: "ㄍㄨㄤ ㄇㄧㄥˊ ㄌㄟˇ ㄌㄨㄛˋ", example: "這件事可以用「光明磊落」來形容。" },
  { full: "問心無愧", blank: "問心無＿", answer: "愧", hint: "慚愧", meaning: "反省自己，沒有什麼可羞愧的。", level: "中等", category: "品德修養", zhuyin: "ㄨㄣˋ ㄒㄧㄣ ㄨˊ ㄎㄨㄟˋ", example: "這件事可以用「問心無愧」來形容。" },
  { full: "誠心誠意", blank: "誠心誠＿", answer: "意", hint: "心意", meaning: "形容非常真誠。", level: "簡單", category: "品德修養", zhuyin: "ㄔㄥˊ ㄒㄧㄣ ㄔㄥˊ ㄧˋ", example: "這件事可以用「誠心誠意」來形容。" },
  { full: "言行一致", blank: "言行一＿", answer: "致", hint: "相同、一樣", meaning: "說的和做的完全相同。", level: "簡單", category: "品德修養", zhuyin: "ㄧㄢˊ ㄒㄧㄥˊ ㄧˊ ㄓˋ", example: "這件事可以用「言行一致」來形容。" },
  { full: "表裡如一", blank: "表裡如＿", answer: "一", hint: "一樣", meaning: "形容外表和內心一致。", level: "中等", category: "品德修養", zhuyin: "ㄅㄧㄠˇ ㄌㄧˇ ㄖㄨˊ ㄧ", example: "這件事可以用「表裡如一」來形容。" },
  { full: "拾金不昧", blank: "拾金不＿", answer: "昧", hint: "隱藏、占有", meaning: "撿到財物不私自占有。", level: "中等", category: "品德修養", zhuyin: "ㄕˊ ㄐㄧㄣ ㄅㄨˋ ㄇㄟˋ", example: "這件事可以用「拾金不昧」來形容。" },
  { full: "助人為樂", blank: "助人為＿", answer: "樂", hint: "快樂", meaning: "把幫助別人當作快樂。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄖㄣˊ ㄨㄟˊ ㄌㄜˋ", example: "這件事可以用「助人為樂」來形容。" },
  { full: "見義勇為", blank: "見義勇＿", answer: "為", hint: "去做", meaning: "看到正義的事就勇敢去做。", level: "中等", category: "品德修養", zhuyin: "ㄐㄧㄢˋ ㄧˋ ㄩㄥˇ ㄨㄟˊ", example: "這件事可以用「見義勇為」來形容。" },
  { full: "捨己為人", blank: "捨己為＿", answer: "人", hint: "他人", meaning: "犧牲自己，幫助別人。", level: "中等", category: "品德修養", zhuyin: "ㄕㄜˇ ㄐㄧˇ ㄨㄟˋ ㄖㄣˊ", example: "這件事可以用「捨己為人」來形容。" },
  { full: "自私自利", blank: "自私自＿", answer: "利", hint: "利益", meaning: "只為自己打算。", level: "簡單", category: "品德修養", zhuyin: "ㄗˋ ㄙ ㄗˋ ㄌㄧˋ", example: "這件事可以用「自私自利」來形容。" },
  { full: "貪得無厭", blank: "貪得無＿", answer: "厭", hint: "滿足", meaning: "貪心而不知滿足。", level: "中等", category: "品德修養", zhuyin: "ㄊㄢ ㄉㄜˊ ㄨˊ ㄧㄢˋ", example: "這件事可以用「貪得無厭」來形容。" },
  { full: "好逸惡勞", blank: "好逸惡＿", answer: "勞", hint: "勞動", meaning: "貪圖安逸，厭惡勞動。", level: "中等", category: "品德修養", zhuyin: "ㄏㄠˋ ㄧˋ ㄨˋ ㄌㄠˊ", example: "這件事可以用「好逸惡勞」來形容。" },
  { full: "勤能補拙", blank: "勤能補＿", answer: "拙", hint: "笨拙、不足", meaning: "勤奮可以彌補能力不足。", level: "中等", category: "學習成語", zhuyin: "ㄑㄧㄣˊ ㄋㄥˊ ㄅㄨˇ ㄓㄨㄛˊ", example: "這件事可以用「勤能補拙」來形容。" },
  { full: "勤學苦練", blank: "勤學苦＿", answer: "練", hint: "練習", meaning: "勤奮學習，刻苦練習。", level: "簡單", category: "學習成語", zhuyin: "ㄑㄧㄣˊ ㄒㄩㄝˊ ㄎㄨˇ ㄌㄧㄢˋ", example: "這件事可以用「勤學苦練」來形容。" },
  { full: "廢寢忘食", blank: "廢寢忘＿", answer: "食", hint: "吃飯", meaning: "形容專心努力，顧不得睡覺吃飯。", level: "中等", category: "學習成語", zhuyin: "ㄈㄟˋ ㄑㄧㄣˇ ㄨㄤˋ ㄕˊ", example: "這件事可以用「廢寢忘食」來形容。" },
  { full: "全神貫注", blank: "全神貫＿", answer: "注", hint: "集中、注入", meaning: "形容注意力高度集中。", level: "中等", category: "學習成語", zhuyin: "ㄑㄩㄢˊ ㄕㄣˊ ㄍㄨㄢˋ ㄓㄨˋ", example: "這件事可以用「全神貫注」來形容。" },
  { full: "一絲不苟", blank: "一絲不＿", answer: "苟", hint: "馬虎", meaning: "形容做事認真，一點也不馬虎。", level: "中等", category: "學習成語", zhuyin: "ㄧˋ ㄙ ㄅㄨˋ ㄍㄡˇ", example: "這件事可以用「一絲不苟」來形容。" },
  { full: "持之以恆", blank: "持之以＿", answer: "恆", hint: "恆心", meaning: "長久堅持下去。", level: "中等", category: "學習成語", zhuyin: "ㄔˊ ㄓ ㄧˇ ㄏㄥˊ", example: "這件事可以用「持之以恆」來形容。" },
  { full: "鍥而不捨", blank: "鍥而不＿", answer: "捨", hint: "放棄", meaning: "比喻有恆心、有毅力。", level: "困難", category: "學習成語", zhuyin: "ㄑㄧㄝˋ ㄦˊ ㄅㄨˋ ㄕㄜˇ", example: "這件事可以用「鍥而不捨」來形容。" },
  { full: "堅持不懈", blank: "堅持不＿", answer: "懈", hint: "鬆懈", meaning: "堅持到底，毫不鬆懈。", level: "中等", category: "學習成語", zhuyin: "ㄐㄧㄢ ㄔˊ ㄅㄨˋ ㄒㄧㄝˋ", example: "這件事可以用「堅持不懈」來形容。" },
  { full: "孜孜以求", blank: "孜孜以＿", answer: "求", hint: "追求", meaning: "勤勉不懈地追求。", level: "中等", category: "學習成語", zhuyin: "ㄗ ㄗ ㄧˇ ㄑㄧㄡˊ", example: "這件事可以用「孜孜以求」來形容。" },
  { full: "博覽群書", blank: "博覽群＿", answer: "書", hint: "書本", meaning: "廣泛閱讀各種書籍。", level: "中等", category: "學習成語", zhuyin: "ㄅㄛˊ ㄌㄢˇ ㄑㄩㄣˊ ㄕㄨ", example: "這件事可以用「博覽群書」來形容。" },
  { full: "學富五車", blank: "學富五＿", answer: "車", hint: "車輛", meaning: "形容讀書很多，學問淵博。", level: "困難", category: "學習成語", zhuyin: "ㄒㄩㄝˊ ㄈㄨˋ ㄨˇ ㄔㄜ", example: "這件事可以用「學富五車」來形容。" },
  { full: "才高八斗", blank: "才高八＿", answer: "斗", hint: "容量單位", meaning: "形容人很有才華。", level: "困難", category: "學習成語", zhuyin: "ㄘㄞˊ ㄍㄠ ㄅㄚ ㄉㄡˇ", example: "這件事可以用「才高八斗」來形容。" },
  { full: "出口成章", blank: "出口成＿", answer: "章", hint: "文章、章法", meaning: "形容文思敏捷，說話成文。", level: "中等", category: "學習成語", zhuyin: "ㄔㄨ ㄎㄡˇ ㄔㄥˊ ㄓㄤ", example: "這件事可以用「出口成章」來形容。" },
  { full: "妙筆生花", blank: "妙筆生＿", answer: "花", hint: "花朵", meaning: "形容寫作能力高明。", level: "中等", category: "學習成語", zhuyin: "ㄇㄧㄠˋ ㄅㄧˇ ㄕㄥ ㄏㄨㄚ", example: "這件事可以用「妙筆生花」來形容。" },
  { full: "下筆成章", blank: "下筆成＿", answer: "章", hint: "文章、章法", meaning: "形容文思敏捷，寫作很快。", level: "中等", category: "學習成語", zhuyin: "ㄒㄧㄚˋ ㄅㄧˇ ㄔㄥˊ ㄓㄤ", example: "這件事可以用「下筆成章」來形容。" },
  { full: "名列前茅", blank: "名列前＿", answer: "茅", hint: "茅草，古代用來標記名次", meaning: "形容成績排在前面。", level: "困難", category: "學習成語", zhuyin: "ㄇㄧㄥˊ ㄌㄧㄝˋ ㄑㄧㄢˊ ㄇㄠˊ", example: "這件事可以用「名列前茅」來形容。" },
  { full: "名落孫山", blank: "名落孫＿", answer: "山", hint: "山名", meaning: "指考試或選拔沒有錄取。", level: "中等", category: "學習成語", zhuyin: "ㄇㄧㄥˊ ㄌㄨㄛˋ ㄙㄨㄣ ㄕㄢ", example: "這件事可以用「名落孫山」來形容。" },
  { full: "功成名就", blank: "功成名＿", answer: "就", hint: "成就", meaning: "功業完成，名聲也建立了。", level: "中等", category: "生活常用", zhuyin: "ㄍㄨㄥ ㄔㄥˊ ㄇㄧㄥˊ ㄐㄧㄡˋ", example: "這件事可以用「功成名就」來形容。" },
  { full: "大器晚成", blank: "大器晚＿", answer: "成", hint: "完成、成熟", meaning: "比喻有大才能的人較晚成功。", level: "中等", category: "生活常用", zhuyin: "ㄉㄚˋ ㄑㄧˋ ㄨㄢˇ ㄔㄥˊ", example: "這件事可以用「大器晚成」來形容。" },
  { full: "日積月累", blank: "日積月＿", answer: "累", hint: "累積", meaning: "長時間一點一滴累積。", level: "簡單", category: "學習成語", zhuyin: "ㄖˋ ㄐㄧ ㄩㄝˋ ㄌㄟˇ", example: "這件事可以用「日積月累」來形容。" },
  { full: "積少成多", blank: "積少成＿", answer: "多", hint: "多的", meaning: "一點一點累積成很多。", level: "簡單", category: "學習成語", zhuyin: "ㄐㄧ ㄕㄠˇ ㄔㄥˊ ㄉㄨㄛ", example: "這件事可以用「積少成多」來形容。" },
  { full: "由淺入深", blank: "由淺入＿", answer: "深", hint: "深奧", meaning: "從簡單逐漸進入困難。", level: "簡單", category: "學習成語", zhuyin: "ㄧㄡˊ ㄑㄧㄢˇ ㄖㄨˋ ㄕㄣ", example: "這件事可以用「由淺入深」來形容。" },
  { full: "深入淺出", blank: "深入淺＿", answer: "出", hint: "表達出來", meaning: "內容深刻，但表達淺顯易懂。", level: "中等", category: "學習成語", zhuyin: "ㄕㄣ ㄖㄨˋ ㄑㄧㄢˇ ㄔㄨ", example: "這件事可以用「深入淺出」來形容。" },
  { full: "觸類旁通", blank: "觸類旁＿", answer: "通", hint: "通達", meaning: "掌握某一事物後，能推知同類事物。", level: "中等", category: "學習成語", zhuyin: "ㄔㄨˋ ㄌㄟˋ ㄆㄤˊ ㄊㄨㄥ", example: "這件事可以用「觸類旁通」來形容。" },
  { full: "茅塞頓開", blank: "茅塞頓＿", answer: "開", hint: "打開", meaning: "形容忽然理解明白。", level: "困難", category: "學習成語", zhuyin: "ㄇㄠˊ ㄙㄜˋ ㄉㄨㄣˋ ㄎㄞ", example: "這件事可以用「茅塞頓開」來形容。" },
  { full: "豁然開朗", blank: "豁然開＿", answer: "朗", hint: "明朗", meaning: "形容突然明白或心情開闊。", level: "中等", category: "學習成語", zhuyin: "ㄏㄨㄛˋ ㄖㄢˊ ㄎㄞ ㄌㄤˇ", example: "這件事可以用「豁然開朗」來形容。" },
  { full: "恍然大悟", blank: "恍然大＿", answer: "悟", hint: "明白、醒悟", meaning: "一下子完全明白。", level: "中等", category: "學習成語", zhuyin: "ㄏㄨㄤˇ ㄖㄢˊ ㄉㄚˋ ㄨˋ", example: "這件事可以用「恍然大悟」來形容。" },
  { full: "一知半解", blank: "一知半＿", answer: "解", hint: "了解", meaning: "知道得不全面，理解不透徹。", level: "簡單", category: "學習成語", zhuyin: "ㄧˋ ㄓ ㄅㄢˋ ㄐㄧㄝˇ", example: "這件事可以用「一知半解」來形容。" },
  { full: "囫圇吞棗", blank: "囫圇吞＿", answer: "棗", hint: "棗子", meaning: "比喻讀書等不加分析地籠統接受。", level: "困難", category: "學習成語", zhuyin: "ㄏㄨˊ ㄌㄨㄣˊ ㄊㄨㄣ ㄗㄠˇ", example: "這件事可以用「囫圇吞棗」來形容。" },
  { full: "生吞活剝", blank: "生吞活＿", answer: "剝", hint: "剝皮", meaning: "比喻生硬地照搬別人的東西。", level: "中等", category: "學習成語", zhuyin: "ㄕㄥ ㄊㄨㄣ ㄏㄨㄛˊ ㄅㄛ", example: "這件事可以用「生吞活剝」來形容。" },
  { full: "望文生義", blank: "望文生＿", answer: "義", hint: "意思", meaning: "不了解詞句真正意思，只從字面猜測。", level: "中等", category: "學習成語", zhuyin: "ㄨㄤˋ ㄨㄣˊ ㄕㄥ ㄧˋ", example: "這件事可以用「望文生義」來形容。" },
  { full: "不求甚解", blank: "不求甚＿", answer: "解", hint: "理解", meaning: "只求知道大概，不求深入了解。", level: "中等", category: "學習成語", zhuyin: "ㄅㄨˋ ㄑㄧㄡˊ ㄕㄣˋ ㄐㄧㄝˇ", example: "這件事可以用「不求甚解」來形容。" },
  { full: "引經據典", blank: "引經據＿", answer: "典", hint: "典籍", meaning: "引用經書或典故作依據。", level: "困難", category: "學習成語", zhuyin: "ㄧㄣˇ ㄐㄧㄥ ㄐㄩˋ ㄉㄧㄢˇ", example: "這件事可以用「引經據典」來形容。" },
  { full: "咬文嚼字", blank: "咬文嚼＿", answer: "字", hint: "文字", meaning: "過分斟酌字句。", level: "中等", category: "學習成語", zhuyin: "ㄧㄠˇ ㄨㄣˊ ㄐㄧㄠˊ ㄗˋ", example: "這件事可以用「咬文嚼字」來形容。" },
  { full: "字斟句酌", blank: "字斟句＿", answer: "酌", hint: "斟酌", meaning: "仔細推敲每個字句。", level: "困難", category: "學習成語", zhuyin: "ㄗˋ ㄓㄣ ㄐㄩˋ ㄓㄨㄛˊ", example: "這件事可以用「字斟句酌」來形容。" },
  { full: "鶴立雞群", blank: "鶴立雞＿", answer: "群", hint: "群體", meaning: "比喻人的才能或儀表特別突出。", level: "中等", category: "動物成語", zhuyin: "ㄏㄜˋ ㄌㄧˋ ㄐㄧ ㄑㄩㄣˊ", example: "這件事可以用「鶴立雞群」來形容。" },
  { full: "雞犬不寧", blank: "雞犬不＿", answer: "寧", hint: "安寧", meaning: "形容騷擾得很厲害。", level: "中等", category: "動物成語", zhuyin: "ㄐㄧ ㄑㄩㄢˇ ㄅㄨˋ ㄋㄧㄥˊ", example: "這件事可以用「雞犬不寧」來形容。" },
  { full: "雞飛狗跳", blank: "雞飛狗＿", answer: "跳", hint: "跳動", meaning: "形容混亂不安。", level: "簡單", category: "動物成語", zhuyin: "ㄐㄧ ㄈㄟ ㄍㄡˇ ㄊㄧㄠˋ", example: "這件事可以用「雞飛狗跳」來形容。" },
  { full: "狼吞虎嚥", blank: "狼吞虎＿", answer: "嚥", hint: "吞嚥", meaning: "形容吃東西又急又猛。", level: "中等", category: "動物成語", zhuyin: "ㄌㄤˊ ㄊㄨㄣ ㄏㄨˇ ㄧㄢˋ", example: "這件事可以用「狼吞虎嚥」來形容。" },
  { full: "狼狽為奸", blank: "狼狽為＿", answer: "奸", hint: "奸詐、壞事", meaning: "比喻壞人互相勾結做壞事。", level: "中等", category: "動物成語", zhuyin: "ㄌㄤˊ ㄅㄟˋ ㄨㄟˊ ㄐㄧㄢ", example: "這件事可以用「狼狽為奸」來形容。" },
  { full: "鼠目寸光", blank: "鼠目寸＿", answer: "光", hint: "光線、眼光", meaning: "形容目光短淺。", level: "簡單", category: "動物成語", zhuyin: "ㄕㄨˇ ㄇㄨˋ ㄘㄨㄣˋ ㄍㄨㄤ", example: "這件事可以用「鼠目寸光」來形容。" },
  { full: "牛刀小試", blank: "牛刀小＿", answer: "試", hint: "試驗", meaning: "比喻有大本領的人先在小事上施展一下。", level: "中等", category: "動物成語", zhuyin: "ㄋㄧㄡˊ ㄉㄠ ㄒㄧㄠˇ ㄕˋ", example: "這件事可以用「牛刀小試」來形容。" },
  { full: "虎頭蛇尾", blank: "虎頭蛇＿", answer: "尾", hint: "尾巴", meaning: "比喻開始聲勢大，後來卻很草率。", level: "簡單", category: "動物成語", zhuyin: "ㄏㄨˇ ㄊㄡˊ ㄕㄜˊ ㄨㄟˇ", example: "這件事可以用「虎頭蛇尾」來形容。" },
  { full: "龍爭虎鬥", blank: "龍爭虎＿", answer: "鬥", hint: "爭鬥", meaning: "形容雙方勢均力敵，競爭激烈。", level: "中等", category: "動物成語", zhuyin: "ㄌㄨㄥˊ ㄓㄥ ㄏㄨˇ ㄉㄡˋ", example: "這件事可以用「龍爭虎鬥」來形容。" },
  { full: "馬到成功", blank: "馬到成＿", answer: "功", hint: "成功", meaning: "形容事情順利，一開始就成功。", level: "簡單", category: "動物成語", zhuyin: "ㄇㄚˇ ㄉㄠˋ ㄔㄥˊ ㄍㄨㄥ", example: "這件事可以用「馬到成功」來形容。" },
  { full: "羊入虎口", blank: "羊入虎＿", answer: "口", hint: "嘴巴", meaning: "比喻陷入危險境地。", level: "簡單", category: "動物成語", zhuyin: "ㄧㄤˊ ㄖㄨˋ ㄏㄨˇ ㄎㄡˇ", example: "這件事可以用「羊入虎口」來形容。" },
  { full: "猴年馬月", blank: "猴年馬＿", answer: "月", hint: "月份", meaning: "指遙遙無期，不知何時。", level: "簡單", category: "動物成語", zhuyin: "ㄏㄡˊ ㄋㄧㄢˊ ㄇㄚˇ ㄩㄝˋ", example: "這件事可以用「猴年馬月」來形容。" },
  { full: "狗急跳牆", blank: "狗急跳＿", answer: "牆", hint: "牆壁", meaning: "比喻人在走投無路時不顧一切。", level: "簡單", category: "動物成語", zhuyin: "ㄍㄡˇ ㄐㄧˊ ㄊㄧㄠˋ ㄑㄧㄤˊ", example: "這件事可以用「狗急跳牆」來形容。" },
  { full: "豬朋狗友", blank: "豬朋狗＿", answer: "友", hint: "朋友", meaning: "指不正派的朋友。", level: "簡單", category: "動物成語", zhuyin: "ㄓㄨ ㄆㄥˊ ㄍㄡˇ ㄧㄡˇ", example: "這件事可以用「豬朋狗友」來形容。" },
  { full: "魚目混珠", blank: "魚目混＿", answer: "珠", hint: "珠子", meaning: "比喻拿假的冒充真的。", level: "中等", category: "動物成語", zhuyin: "ㄩˊ ㄇㄨˋ ㄏㄨㄣˋ ㄓㄨ", example: "這件事可以用「魚目混珠」來形容。" },
  { full: "如魚得水", blank: "如魚得＿", answer: "水", hint: "水", meaning: "比喻得到適合自己的環境或依靠。", level: "簡單", category: "動物成語", zhuyin: "ㄖㄨˊ ㄩˊ ㄉㄜˊ ㄕㄨㄟˇ", example: "這件事可以用「如魚得水」來形容。" },
  { full: "沉魚落雁", blank: "沉魚落＿", answer: "雁", hint: "雁鳥", meaning: "形容女子容貌美麗。", level: "中等", category: "動物成語", zhuyin: "ㄔㄣˊ ㄩˊ ㄌㄨㄛˋ ㄧㄢˋ", example: "這件事可以用「沉魚落雁」來形容。" },
  { full: "驚弓之鳥", blank: "驚弓之＿", answer: "鳥", hint: "鳥類", meaning: "比喻受過驚嚇，遇事就害怕的人。", level: "中等", category: "動物成語", zhuyin: "ㄐㄧㄥ ㄍㄨㄥ ㄓ ㄋㄧㄠˇ", example: "這件事可以用「驚弓之鳥」來形容。" },
  { full: "飛蛾撲火", blank: "飛蛾撲＿", answer: "火", hint: "火焰", meaning: "比喻自取滅亡。", level: "中等", category: "動物成語", zhuyin: "ㄈㄟ ㄜˊ ㄆㄨ ㄏㄨㄛˇ", example: "這件事可以用「飛蛾撲火」來形容。" },
  { full: "蛛絲馬跡", blank: "蛛絲馬＿", answer: "跡", hint: "痕跡", meaning: "比喻事情留下的細微線索。", level: "中等", category: "動物成語", zhuyin: "ㄓㄨ ㄙ ㄇㄚˇ ㄐㄧ", example: "這件事可以用「蛛絲馬跡」來形容。" },
  { full: "盲人摸象", blank: "盲人摸＿", answer: "象", hint: "大象", meaning: "比喻只了解局部，不能看清全貌。", level: "中等", category: "故事寓言", zhuyin: "ㄇㄤˊ ㄖㄣˊ ㄇㄛ ㄒㄧㄤˋ", example: "這件事可以用「盲人摸象」來形容。" },
  { full: "塞翁失馬", blank: "塞翁失＿", answer: "馬", hint: "馬", meaning: "比喻禍福難以預料。", level: "中等", category: "故事寓言", zhuyin: "ㄙㄞˋ ㄨㄥ ㄕ ㄇㄚˇ", example: "這件事可以用「塞翁失馬」來形容。" },
  { full: "葉公好龍", blank: "葉公好＿", answer: "龍", hint: "龍", meaning: "比喻表面喜愛，實際並不真愛。", level: "中等", category: "故事寓言", zhuyin: "ㄧㄝˋ ㄍㄨㄥ ㄏㄠˋ ㄌㄨㄥˊ", example: "這件事可以用「葉公好龍」來形容。" },
  { full: "曲突徙薪", blank: "曲突徙＿", answer: "薪", hint: "柴薪", meaning: "比喻事先採取措施，防止災禍。", level: "困難", category: "故事寓言", zhuyin: "ㄑㄩ ㄊㄨˊ ㄒㄧˇ ㄒㄧㄣ", example: "這件事可以用「曲突徙薪」來形容。" },
  { full: "螳臂當車", blank: "螳臂當＿", answer: "車", hint: "車輛", meaning: "比喻力量不足卻硬要抵抗。", level: "困難", category: "故事寓言", zhuyin: "ㄊㄤˊ ㄅㄧˋ ㄉㄤ ㄔㄜ", example: "這件事可以用「螳臂當車」來形容。" },
  { full: "朝三暮四", blank: "朝三暮＿", answer: "四", hint: "四", meaning: "比喻反覆無常，變來變去。", level: "簡單", category: "數字成語", zhuyin: "ㄓㄠ ㄙㄢ ㄇㄨˋ ㄙˋ", example: "這件事可以用「朝三暮四」來形容。" },
  { full: "一舉兩得", blank: "一舉兩＿", answer: "得", hint: "得到", meaning: "做一件事得到兩種好處。", level: "簡單", category: "數字成語", zhuyin: "ㄧˋ ㄐㄩˇ ㄌㄧㄤˇ ㄉㄜˊ", example: "這件事可以用「一舉兩得」來形容。" },
  { full: "一五一十", blank: "一五一＿", answer: "十", hint: "十", meaning: "形容從頭到尾原原本本地說出來。", level: "簡單", category: "數字成語", zhuyin: "ㄧ ㄨˇ ㄧ ㄕˊ", example: "這件事可以用「一五一十」來形容。" },
  { full: "一清二楚", blank: "一清二＿", answer: "楚", hint: "清楚", meaning: "形容非常清楚明白。", level: "簡單", category: "數字成語", zhuyin: "ㄧˋ ㄑㄧㄥ ㄦˋ ㄔㄨˇ", example: "這件事可以用「一清二楚」來形容。" },
  { full: "一模一樣", blank: "一模一＿", answer: "樣", hint: "樣子", meaning: "形容完全相同。", level: "簡單", category: "數字成語", zhuyin: "ㄧˋ ㄇㄨˊ ㄧˊ ㄧㄤˋ", example: "這件事可以用「一模一樣」來形容。" },
  { full: "三言兩語", blank: "三言兩＿", answer: "語", hint: "語言", meaning: "幾句話，形容話很少。", level: "簡單", category: "數字成語", zhuyin: "ㄙㄢ ㄧㄢˊ ㄌㄧㄤˇ ㄩˇ", example: "這件事可以用「三言兩語」來形容。" },
  { full: "三長兩短", blank: "三長兩＿", answer: "短", hint: "短", meaning: "指意外災禍或不幸。", level: "中等", category: "數字成語", zhuyin: "ㄙㄢ ㄔㄤˊ ㄌㄧㄤˇ ㄉㄨㄢˇ", example: "這件事可以用「三長兩短」來形容。" },
  { full: "四通八達", blank: "四通八＿", answer: "達", hint: "到達", meaning: "形容交通便利，通向各方。", level: "中等", category: "數字成語", zhuyin: "ㄙˋ ㄊㄨㄥ ㄅㄚ ㄉㄚˊ", example: "這件事可以用「四通八達」來形容。" },
  { full: "五光十色", blank: "五光十＿", answer: "色", hint: "顏色", meaning: "形容色彩鮮豔、種類繁多。", level: "簡單", category: "數字成語", zhuyin: "ㄨˇ ㄍㄨㄤ ㄕˊ ㄙㄜˋ", example: "這件事可以用「五光十色」來形容。" },
  { full: "七嘴八舌", blank: "七嘴八＿", answer: "舌", hint: "舌頭", meaning: "形容人多嘴雜，議論紛紛。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧ ㄗㄨㄟˇ ㄅㄚ ㄕㄜˊ", example: "這件事可以用「七嘴八舌」來形容。" },
  { full: "九死一生", blank: "九死一＿", answer: "生", hint: "生命", meaning: "形容經歷極大危險而倖存。", level: "中等", category: "數字成語", zhuyin: "ㄐㄧㄡˇ ㄙˇ ㄧˋ ㄕㄥ", example: "這件事可以用「九死一生」來形容。" },
  { full: "十拿九穩", blank: "十拿九＿", answer: "穩", hint: "穩當", meaning: "形容非常有把握。", level: "簡單", category: "數字成語", zhuyin: "ㄕˊ ㄋㄚˊ ㄐㄧㄡˇ ㄨㄣˇ", example: "這件事可以用「十拿九穩」來形容。" },
  { full: "千方百計", blank: "千方百＿", answer: "計", hint: "計策", meaning: "想盡各種辦法。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧㄢ ㄈㄤ ㄅㄞˇ ㄐㄧˋ", example: "這件事可以用「千方百計」來形容。" },
  { full: "千軍萬馬", blank: "千軍萬＿", answer: "馬", hint: "馬匹", meaning: "形容兵馬很多，聲勢浩大。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧㄢ ㄐㄩㄣ ㄨㄢˋ ㄇㄚˇ", example: "這件事可以用「千軍萬馬」來形容。" },
  { full: "千言萬語", blank: "千言萬＿", answer: "語", hint: "語言", meaning: "形容話很多。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧㄢ ㄧㄢˊ ㄨㄢˋ ㄩˇ", example: "這件事可以用「千言萬語」來形容。" },
  { full: "千山萬水", blank: "千山萬＿", answer: "水", hint: "水", meaning: "形容路途遙遠。", level: "簡單", category: "數字成語", zhuyin: "ㄑㄧㄢ ㄕㄢ ㄨㄢˋ ㄕㄨㄟˇ", example: "這件事可以用「千山萬水」來形容。" },
  { full: "萬紫千紅", blank: "萬紫千＿", answer: "紅", hint: "紅色", meaning: "形容花色繁多，也比喻事物豐富多彩。", level: "簡單", category: "數字成語", zhuyin: "ㄨㄢˋ ㄗˇ ㄑㄧㄢ ㄏㄨㄥˊ", example: "這件事可以用「萬紫千紅」來形容。" },
  { full: "百花齊放", blank: "百花齊＿", answer: "放", hint: "開放", meaning: "形容各種花同時盛開，也比喻不同形式自由發展。", level: "簡單", category: "自然成語", zhuyin: "ㄅㄞˇ ㄏㄨㄚ ㄑㄧˊ ㄈㄤˋ", example: "這件事可以用「百花齊放」來形容。" },
  { full: "花團錦簇", blank: "花團錦＿", answer: "簇", hint: "聚集成團", meaning: "形容花朵繁多、色彩華麗。", level: "困難", category: "自然成語", zhuyin: "ㄏㄨㄚ ㄊㄨㄢˊ ㄐㄧㄣˇ ㄘㄨˋ", example: "這件事可以用「花團錦簇」來形容。" },
  { full: "綠草如茵", blank: "綠草如＿", answer: "茵", hint: "墊子、草地柔軟", meaning: "形容草地碧綠柔軟。", level: "中等", category: "自然成語", zhuyin: "ㄌㄩˋ ㄘㄠˇ ㄖㄨˊ ㄧㄣ", example: "這件事可以用「綠草如茵」來形容。" },
  { full: "枝繁葉茂", blank: "枝繁葉＿", answer: "茂", hint: "茂盛", meaning: "形容樹木枝葉繁密。", level: "簡單", category: "自然成語", zhuyin: "ㄓ ㄈㄢˊ ㄧㄝˋ ㄇㄠˋ", example: "這件事可以用「枝繁葉茂」來形容。" },
  { full: "春華秋實", blank: "春華秋＿", answer: "實", hint: "果實", meaning: "比喻有耕耘就有收穫。", level: "中等", category: "自然成語", zhuyin: "ㄔㄨㄣ ㄏㄨㄚˊ ㄑㄧㄡ ㄕˊ", example: "這件事可以用「春華秋實」來形容。" },
  { full: "秋高氣爽", blank: "秋高氣＿", answer: "爽", hint: "清爽", meaning: "形容秋天天空晴朗，氣候涼爽。", level: "簡單", category: "自然成語", zhuyin: "ㄑㄧㄡ ㄍㄠ ㄑㄧˋ ㄕㄨㄤˇ", example: "這件事可以用「秋高氣爽」來形容。" },
  { full: "冰天雪地", blank: "冰天雪＿", answer: "地", hint: "地面", meaning: "形容冰雪漫天蓋地。", level: "簡單", category: "自然成語", zhuyin: "ㄅㄧㄥ ㄊㄧㄢ ㄒㄩㄝˇ ㄉㄧˋ", example: "這件事可以用「冰天雪地」來形容。" },
  { full: "山窮水盡", blank: "山窮水＿", answer: "盡", hint: "盡頭", meaning: "形容陷入困境，沒有出路。", level: "中等", category: "自然成語", zhuyin: "ㄕㄢ ㄑㄩㄥˊ ㄕㄨㄟˇ ㄐㄧㄣˋ", example: "這件事可以用「山窮水盡」來形容。" },
  { full: "波濤洶湧", blank: "波濤洶＿", answer: "湧", hint: "湧動", meaning: "形容波浪又大又急。", level: "中等", category: "自然成語", zhuyin: "ㄅㄛ ㄊㄠˊ ㄒㄩㄥ ㄩㄥˇ", example: "這件事可以用「波濤洶湧」來形容。" },
  { full: "驚濤駭浪", blank: "驚濤駭＿", answer: "浪", hint: "波浪", meaning: "形容風浪很大，也比喻險惡環境。", level: "中等", category: "自然成語", zhuyin: "ㄐㄧㄥ ㄊㄠˊ ㄏㄞˋ ㄌㄤˋ", example: "這件事可以用「驚濤駭浪」來形容。" },
  { full: "風雨交加", blank: "風雨交＿", answer: "加", hint: "增加、加上", meaning: "形容風雨一起襲來。", level: "簡單", category: "自然成語", zhuyin: "ㄈㄥ ㄩˇ ㄐㄧㄠ ㄐㄧㄚ", example: "這件事可以用「風雨交加」來形容。" },
  { full: "雷聲大作", blank: "雷聲大＿", answer: "作", hint: "發作、響起", meaning: "形容雷聲響亮。", level: "簡單", category: "自然成語", zhuyin: "ㄌㄟˊ ㄕㄥ ㄉㄚˋ ㄗㄨㄛˋ", example: "這件事可以用「雷聲大作」來形容。" },
  { full: "晴空萬里", blank: "晴空萬＿", answer: "里", hint: "距離單位", meaning: "形容天空晴朗遼闊。", level: "簡單", category: "自然成語", zhuyin: "ㄑㄧㄥˊ ㄎㄨㄥ ㄨㄢˋ ㄌㄧˇ", example: "這件事可以用「晴空萬里」來形容。" }
,
  { full: "安居樂業", blank: "安居樂＿", answer: "業", hint: "工作、職業", meaning: "生活安定，工作愉快。", level: "簡單", category: "生活常用", zhuyin: "ㄢ ㄐㄩ ㄌㄜˋ ㄧㄝˋ", example: "大家安居樂業，社區充滿活力。" },
  { full: "拔刀相助", blank: "拔刀相＿", answer: "助", hint: "幫忙", meaning: "比喻見義勇為，幫助受欺負的人。", level: "中等", category: "品德修養", zhuyin: "ㄅㄚˊ ㄉㄠ ㄒㄧㄤ ㄓㄨˋ", example: "看到同學被欺負，他立刻拔刀相助。" },
  { full: "白手起家", blank: "白手起＿", answer: "家", hint: "家庭、事業", meaning: "形容沒有基礎或資本而創立事業。", level: "中等", category: "生活常用", zhuyin: "ㄅㄞˊ ㄕㄡˇ ㄑㄧˇ ㄐㄧㄚ", example: "他靠努力白手起家，創辦自己的公司。" },
  { full: "半信半疑", blank: "半信半＿", answer: "疑", hint: "懷疑", meaning: "有點相信又有點懷疑。", level: "簡單", category: "生活常用", zhuyin: "ㄅㄢˋ ㄒㄧㄣˋ ㄅㄢˋ ㄧˊ", example: "他說的故事太奇怪，大家半信半疑。" },
  { full: "包羅萬象", blank: "包羅萬＿", answer: "象", hint: "樣子、現象", meaning: "形容內容豐富，應有盡有。", level: "中等", category: "生活常用", zhuyin: "ㄅㄠ ㄌㄨㄛˊ ㄨㄢˋ ㄒㄧㄤˋ", example: "這本百科全書包羅萬象。" },
  { full: "閉門造車", blank: "閉門造＿", answer: "車", hint: "交通工具", meaning: "比喻不管實際情況，只憑主觀辦事。", level: "中等", category: "故事寓言", zhuyin: "ㄅㄧˋ ㄇㄣˊ ㄗㄠˋ ㄔㄜ", example: "設計產品不能閉門造車，要了解使用者需求。" },
  { full: "變本加厲", blank: "變本加＿", answer: "厲", hint: "更加嚴重", meaning: "情況比原來更加嚴重。", level: "中等", category: "生活常用", zhuyin: "ㄅㄧㄢˋ ㄅㄣˇ ㄐㄧㄚ ㄌㄧˋ", example: "他不但沒改正，反而變本加厲。" },
  { full: "不可思議", blank: "不可思＿", answer: "議", hint: "議論、想像", meaning: "形容無法想像或難以理解。", level: "簡單", category: "生活常用", zhuyin: "ㄅㄨˋ ㄎㄜˇ ㄙ ㄧˋ", example: "這個魔術真是不可思議。" },
  { full: "不勞而獲", blank: "不勞而＿", answer: "獲", hint: "得到", meaning: "沒有付出勞力卻想得到成果。", level: "中等", category: "品德修養", zhuyin: "ㄅㄨˋ ㄌㄠˊ ㄦˊ ㄏㄨㄛˋ", example: "不要幻想不勞而獲。" },
  { full: "不屈不撓", blank: "不屈不＿", answer: "撓", hint: "屈服", meaning: "形容意志堅強，不向困難低頭。", level: "中等", category: "品德修養", zhuyin: "ㄅㄨˋ ㄑㄩ ㄅㄨˋ ㄋㄠˊ", example: "他以不屈不撓的精神完成任務。" },
  { full: "不速之客", blank: "不速之＿", answer: "客", hint: "客人", meaning: "沒有邀請而自己來的客人。", level: "中等", category: "生活常用", zhuyin: "ㄅㄨˋ ㄙㄨˋ ㄓ ㄎㄜˋ", example: "這隻小貓成了家中的不速之客。" },
  { full: "不翼而飛", blank: "不翼而＿", answer: "飛", hint: "飛走", meaning: "比喻東西突然不見了。", level: "中等", category: "生活常用", zhuyin: "ㄅㄨˋ ㄧˋ ㄦˊ ㄈㄟ", example: "桌上的鉛筆竟然不翼而飛。" },
  { full: "滄海桑田", blank: "滄海桑＿", answer: "田", hint: "田地", meaning: "比喻世事變化很大。", level: "困難", category: "自然成語", zhuyin: "ㄘㄤ ㄏㄞˇ ㄙㄤ ㄊㄧㄢˊ", example: "多年後重回故鄉，真有滄海桑田之感。" },
  { full: "操之過急", blank: "操之過＿", answer: "急", hint: "急躁", meaning: "做事太急躁，反而不好。", level: "中等", category: "生活常用", zhuyin: "ㄘㄠ ㄓ ㄍㄨㄛˋ ㄐㄧˊ", example: "學新技能不能操之過急。" },
  { full: "層出不窮", blank: "層出不＿", answer: "窮", hint: "盡頭", meaning: "接連出現，沒有窮盡。", level: "中等", category: "生活常用", zhuyin: "ㄘㄥˊ ㄔㄨ ㄅㄨˋ ㄑㄩㄥˊ", example: "新的創意層出不窮。" },
  { full: "察言觀色", blank: "察言觀＿", answer: "色", hint: "臉色", meaning: "觀察別人的話語和臉色。", level: "中等", category: "生活常用", zhuyin: "ㄔㄚˊ ㄧㄢˊ ㄍㄨㄢ ㄙㄜˋ", example: "服務人員要懂得察言觀色。" },
  { full: "長驅直入", blank: "長驅直＿", answer: "入", hint: "進入", meaning: "軍隊快速前進，深入敵方。", level: "困難", category: "歷史故事", zhuyin: "ㄔㄤˊ ㄑㄩ ㄓˊ ㄖㄨˋ", example: "球隊一路長驅直入打進決賽。" },
  { full: "承先啟後", blank: "承先啟＿", answer: "後", hint: "後面", meaning: "承接前人，開創後來。", level: "中等", category: "學習成語", zhuyin: "ㄔㄥˊ ㄒㄧㄢ ㄑㄧˇ ㄏㄡˋ", example: "這位老師在教育上承先啟後。" },
  { full: "赤手空拳", blank: "赤手空＿", answer: "拳", hint: "拳頭", meaning: "形容兩手空空，沒有武器或工具。", level: "簡單", category: "生活常用", zhuyin: "ㄔˋ ㄕㄡˇ ㄎㄨㄥ ㄑㄩㄢˊ", example: "他赤手空拳完成挑戰。" },
  { full: "重見天日", blank: "重見天＿", answer: "日", hint: "太陽", meaning: "比喻脫離黑暗困境，重新見到光明。", level: "中等", category: "生活常用", zhuyin: "ㄔㄨㄥˊ ㄐㄧㄢˋ ㄊㄧㄢ ㄖˋ", example: "失而復得的資料終於重見天日。" },
  { full: "垂涎三尺", blank: "垂涎三＿", answer: "尺", hint: "長度單位", meaning: "形容非常想吃或非常羨慕。", level: "中等", category: "生活常用", zhuyin: "ㄔㄨㄟˊ ㄒㄧㄢˊ ㄙㄢ ㄔˇ", example: "大家看著美食垂涎三尺。" },
  { full: "從容不迫", blank: "從容不＿", answer: "迫", hint: "急迫", meaning: "態度鎮定，不慌不忙。", level: "中等", category: "品德修養", zhuyin: "ㄘㄨㄥ ㄖㄨㄥˊ ㄅㄨˋ ㄆㄛˋ", example: "面對考試，他從容不迫。" },
  { full: "措手不及", blank: "措手不＿", answer: "及", hint: "來得及", meaning: "事情突然發生，來不及應付。", level: "中等", category: "生活常用", zhuyin: "ㄘㄨㄛˋ ㄕㄡˇ ㄅㄨˋ ㄐㄧˊ", example: "突如其來的大雨讓人措手不及。" },
  { full: "大材小用", blank: "大材小＿", answer: "用", hint: "使用", meaning: "把大才能用在小地方。", level: "簡單", category: "生活常用", zhuyin: "ㄉㄚˋ ㄘㄞˊ ㄒㄧㄠˇ ㄩㄥˋ", example: "讓專家只做雜事，實在大材小用。" },
  { full: "大海撈針", blank: "大海撈＿", answer: "針", hint: "細小工具", meaning: "比喻很難找到。", level: "簡單", category: "生活常用", zhuyin: "ㄉㄚˋ ㄏㄞˇ ㄌㄠ ㄓㄣ", example: "在資料中找錯字像大海撈針。" },
  { full: "大同小異", blank: "大同小＿", answer: "異", hint: "不同", meaning: "大致相同，稍有差異。", level: "簡單", category: "生活常用", zhuyin: "ㄉㄚˋ ㄊㄨㄥˊ ㄒㄧㄠˇ ㄧˋ", example: "這兩個方案大同小異。" },
  { full: "得寸進尺", blank: "得寸進＿", answer: "尺", hint: "長度單位", meaning: "比喻貪得無厭，要求越來越多。", level: "中等", category: "生活常用", zhuyin: "ㄉㄜˊ ㄘㄨㄣˋ ㄐㄧㄣˋ ㄔˇ", example: "別得寸進尺，要懂得感謝。" },
  { full: "滴水穿石", blank: "滴水穿＿", answer: "石", hint: "石頭", meaning: "比喻只要有恆心，微小力量也能成功。", level: "簡單", category: "品德修養", zhuyin: "ㄉㄧ ㄕㄨㄟˇ ㄔㄨㄢ ㄕˊ", example: "每天練習，終能滴水穿石。" },
  { full: "獨一無二", blank: "獨一無＿", answer: "二", hint: "數字", meaning: "只有一個，沒有相同的。", level: "簡單", category: "生活常用", zhuyin: "ㄉㄨˊ ㄧ ㄨˊ ㄦˋ", example: "每個人的想法都是獨一無二的。" },
  { full: "對症下藥", blank: "對症下＿", answer: "藥", hint: "藥物", meaning: "比喻針對問題採取有效方法。", level: "中等", category: "生活常用", zhuyin: "ㄉㄨㄟˋ ㄓㄥˋ ㄒㄧㄚˋ ㄧㄠˋ", example: "找出原因才能對症下藥。" },
  { full: "耳目一新", blank: "耳目一＿", answer: "新", hint: "新的", meaning: "聽到看到都覺得新鮮。", level: "簡單", category: "生活常用", zhuyin: "ㄦˇ ㄇㄨˋ ㄧˋ ㄒㄧㄣ", example: "這次展覽讓人耳目一新。" },
  { full: "發憤圖強", blank: "發憤圖＿", answer: "強", hint: "強盛", meaning: "下定決心努力向上。", level: "中等", category: "品德修養", zhuyin: "ㄈㄚ ㄈㄣˋ ㄊㄨˊ ㄑㄧㄤˊ", example: "他失敗後發憤圖強。" },
  { full: "翻山越嶺", blank: "翻山越＿", answer: "嶺", hint: "山嶺", meaning: "形容長途跋涉，非常辛苦。", level: "中等", category: "自然成語", zhuyin: "ㄈㄢ ㄕㄢ ㄩㄝˋ ㄌㄧㄥˇ", example: "救援隊翻山越嶺抵達村莊。" },
  { full: "返老還童", blank: "返老還＿", answer: "童", hint: "兒童", meaning: "形容老人恢復青春活力。", level: "中等", category: "生活常用", zhuyin: "ㄈㄢˇ ㄌㄠˇ ㄏㄨㄢˊ ㄊㄨㄥˊ", example: "爺爺運動後像返老還童。" },
  { full: "分秒必爭", blank: "分秒必＿", answer: "爭", hint: "爭取", meaning: "一分一秒都要爭取。", level: "簡單", category: "學習成語", zhuyin: "ㄈㄣ ㄇㄧㄠˇ ㄅㄧˋ ㄓㄥ", example: "考前複習要分秒必爭。" },
  { full: "風馳電掣", blank: "風馳電＿", answer: "掣", hint: "快速閃過", meaning: "形容速度非常快。", level: "困難", category: "自然成語", zhuyin: "ㄈㄥ ㄔˊ ㄉㄧㄢˋ ㄔㄜˋ", example: "賽車風馳電掣般衝過終點。" },
  { full: "風花雪月", blank: "風花雪＿", answer: "月", hint: "月亮", meaning: "泛指四季景色，也指詩文中的浪漫題材。", level: "中等", category: "自然成語", zhuyin: "ㄈㄥ ㄏㄨㄚ ㄒㄩㄝˇ ㄩㄝˋ", example: "古詩常寫風花雪月。" },
  { full: "風起雲湧", blank: "風起雲＿", answer: "湧", hint: "湧動", meaning: "形容事物迅速興起，聲勢浩大。", level: "中等", category: "自然成語", zhuyin: "ㄈㄥ ㄑㄧˇ ㄩㄣˊ ㄩㄥˇ", example: "科技發展風起雲湧。" },
  { full: "改過自新", blank: "改過自＿", answer: "新", hint: "新的", meaning: "改正錯誤，重新做人。", level: "簡單", category: "品德修養", zhuyin: "ㄍㄞˇ ㄍㄨㄛˋ ㄗˋ ㄒㄧㄣ", example: "犯錯後要願意改過自新。" },
  { full: "高枕無憂", blank: "高枕無＿", answer: "憂", hint: "憂慮", meaning: "形容沒有顧慮，可以安心。", level: "中等", category: "生活常用", zhuyin: "ㄍㄠ ㄓㄣˇ ㄨˊ ㄧㄡ", example: "完成備份後就能高枕無憂。" },
  { full: "各抒己見", blank: "各抒己＿", answer: "見", hint: "看法", meaning: "各自表達自己的意見。", level: "中等", category: "生活常用", zhuyin: "ㄍㄜˋ ㄕㄨ ㄐㄧˇ ㄐㄧㄢˋ", example: "討論時大家各抒己見。" },
  { full: "根深蒂固", blank: "根深蒂＿", answer: "固", hint: "牢固", meaning: "比喻基礎穩固，不容易動搖。", level: "中等", category: "生活常用", zhuyin: "ㄍㄣ ㄕㄣ ㄉㄧˋ ㄍㄨˋ", example: "這種觀念根深蒂固。" },
  { full: "孤掌難鳴", blank: "孤掌難＿", answer: "鳴", hint: "發聲", meaning: "比喻一個人力量有限，難以成事。", level: "中等", category: "生活常用", zhuyin: "ㄍㄨ ㄓㄤˇ ㄋㄢˊ ㄇㄧㄥˊ", example: "團隊合作很重要，孤掌難鳴。" },
  { full: "固步自封", blank: "固步自＿", answer: "封", hint: "封閉", meaning: "比喻守舊不求進步。", level: "中等", category: "品德修養", zhuyin: "ㄍㄨˋ ㄅㄨˋ ㄗˋ ㄈㄥ", example: "學習不能固步自封。" },
  { full: "刮目相看", blank: "刮目相＿", answer: "看", hint: "觀看", meaning: "用新的眼光看待別人。", level: "中等", category: "生活常用", zhuyin: "ㄍㄨㄚ ㄇㄨˋ ㄒㄧㄤ ㄎㄢˋ", example: "他的進步讓大家刮目相看。" },
  { full: "光陰似箭", blank: "光陰似＿", answer: "箭", hint: "箭矢", meaning: "形容時間過得很快。", level: "簡單", category: "學習成語", zhuyin: "ㄍㄨㄤ ㄧㄣ ㄙˋ ㄐㄧㄢˋ", example: "光陰似箭，暑假很快就過去了。" },
  { full: "海底撈針", blank: "海底撈＿", answer: "針", hint: "細小工具", meaning: "比喻很難尋找。", level: "中等", category: "生活常用", zhuyin: "ㄏㄞˇ ㄉㄧˇ ㄌㄠ ㄓㄣ", example: "在茫茫人海找他像海底撈針。" },
  { full: "汗牛充棟", blank: "汗牛充＿", answer: "棟", hint: "屋梁", meaning: "形容書籍非常多。", level: "困難", category: "學習成語", zhuyin: "ㄏㄢˋ ㄋㄧㄡˊ ㄔㄨㄥ ㄉㄨㄥˋ", example: "圖書館藏書汗牛充棟。" },
  { full: "好高騖遠", blank: "好高騖＿", answer: "遠", hint: "遠方", meaning: "不切實際地追求過高目標。", level: "中等", category: "品德修養", zhuyin: "ㄏㄠˋ ㄍㄠ ㄨˋ ㄩㄢˇ", example: "做人不能好高騖遠。" },
  { full: "和顏悅色", blank: "和顏悅＿", answer: "色", hint: "臉色", meaning: "形容態度溫和親切。", level: "簡單", category: "品德修養", zhuyin: "ㄏㄜˊ ㄧㄢˊ ㄩㄝˋ ㄙㄜˋ", example: "老師和顏悅色地回答問題。" },
  { full: "後生可畏", blank: "後生可＿", answer: "畏", hint: "敬畏", meaning: "年輕人有潛力，值得敬畏。", level: "中等", category: "學習成語", zhuyin: "ㄏㄡˋ ㄕㄥ ㄎㄜˇ ㄨㄟˋ", example: "這位年輕選手表現亮眼，真是後生可畏。" },
  { full: "呼風喚雨", blank: "呼風喚＿", answer: "雨", hint: "雨水", meaning: "比喻有很大的能力或影響力。", level: "中等", category: "自然成語", zhuyin: "ㄏㄨ ㄈㄥ ㄏㄨㄢˋ ㄩˇ", example: "科技讓人類像能呼風喚雨。" },
  { full: "化險為夷", blank: "化險為＿", answer: "夷", hint: "平安", meaning: "把危險轉為平安。", level: "中等", category: "生活常用", zhuyin: "ㄏㄨㄚˋ ㄒㄧㄢˇ ㄨㄟˊ ㄧˊ", example: "冷靜處理讓危機化險為夷。" },
  { full: "揮汗如雨", blank: "揮汗如＿", answer: "雨", hint: "雨水", meaning: "形容流汗很多。", level: "簡單", category: "自然成語", zhuyin: "ㄏㄨㄟ ㄏㄢˋ ㄖㄨˊ ㄩˇ", example: "球員在球場上揮汗如雨。" },
  { full: "繪聲繪色", blank: "繪聲繪＿", answer: "色", hint: "色彩", meaning: "形容敘述或描寫生動逼真。", level: "中等", category: "學習成語", zhuyin: "ㄏㄨㄟˋ ㄕㄥ ㄏㄨㄟˋ ㄙㄜˋ", example: "他把故事說得繪聲繪色。" },
  { full: "機不可失", blank: "機不可＿", answer: "失", hint: "失去", meaning: "好機會不可錯過。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧ ㄅㄨˋ ㄎㄜˇ ㄕ", example: "機不可失，要把握這次比賽。" },
  { full: "雞鳴狗盜", blank: "雞鳴狗＿", answer: "盜", hint: "偷盜", meaning: "比喻微不足道的技能，也可指小偷小摸。", level: "困難", category: "歷史故事", zhuyin: "ㄐㄧ ㄇㄧㄥˊ ㄍㄡˇ ㄉㄠˋ", example: "他靠雞鳴狗盜的小技巧逃過一劫。" },
  { full: "集思廣益", blank: "集思廣＿", answer: "益", hint: "好處", meaning: "集中大家的智慧，得到更好的效果。", level: "中等", category: "學習成語", zhuyin: "ㄐㄧˊ ㄙ ㄍㄨㄤˇ ㄧˋ", example: "團隊討論可以集思廣益。" },
  { full: "家喻戶曉", blank: "家喻戶＿", answer: "曉", hint: "知道", meaning: "每家每戶都知道。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄚ ㄩˋ ㄏㄨˋ ㄒㄧㄠˇ", example: "這首歌家喻戶曉。" },
  { full: "艱苦卓絕", blank: "艱苦卓＿", answer: "絕", hint: "極端", meaning: "形容非常艱難困苦，超乎尋常。", level: "困難", category: "品德修養", zhuyin: "ㄐㄧㄢ ㄎㄨˇ ㄓㄨㄛˊ ㄐㄩㄝˊ", example: "登山隊經歷艱苦卓絕的挑戰。" }
,
  { full: "急中生智", blank: "急中生＿", answer: "智", hint: "智慧", meaning: "危急時突然想出好辦法。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧˊ ㄓㄨㄥ ㄕㄥ ㄓˋ", example: "他在急中生智下解決問題。" },
  { full: "見多識廣", blank: "見多識＿", answer: "廣", hint: "廣博", meaning: "見聞多，知識廣。", level: "簡單", category: "學習成語", zhuyin: "ㄐㄧㄢˋ ㄉㄨㄛ ㄕˋ ㄍㄨㄤˇ", example: "旅行能讓人見多識廣。" },
  { full: "見賢思齊", blank: "見賢思＿", answer: "齊", hint: "看齊", meaning: "看到賢能的人，就想向他學習。", level: "中等", category: "品德修養", zhuyin: "ㄐㄧㄢˋ ㄒㄧㄢˊ ㄙ ㄑㄧˊ", example: "我們要見賢思齊，不斷進步。" },
  { full: "腳踏實地", blank: "腳踏實＿", answer: "地", hint: "地面", meaning: "做事踏實認真，不浮誇。", level: "簡單", category: "品德修養", zhuyin: "ㄐㄧㄠˇ ㄊㄚˋ ㄕˊ ㄉㄧˋ", example: "學習要腳踏實地。" },
  { full: "捷足先登", blank: "捷足先＿", answer: "登", hint: "登上", meaning: "行動快的人先達到目的。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄝˊ ㄗㄨˊ ㄒㄧㄢ ㄉㄥ", example: "機會有限，捷足先登。" },
  { full: "竭盡全力", blank: "竭盡全＿", answer: "力", hint: "力量", meaning: "用盡全部力量。", level: "簡單", category: "品德修養", zhuyin: "ㄐㄧㄝˊ ㄐㄧㄣˋ ㄑㄩㄢˊ ㄌㄧˋ", example: "他竭盡全力完成比賽。" },
  { full: "今非昔比", blank: "今非昔＿", answer: "比", hint: "比較", meaning: "現在已不是過去能相比的。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄣ ㄈㄟ ㄒㄧˊ ㄅㄧˇ", example: "這座城市發展快速，今非昔比。" },
  { full: "津津有味", blank: "津津有＿", answer: "味", hint: "味道", meaning: "形容興趣濃厚或吃得很有滋味。", level: "簡單", category: "生活常用", zhuyin: "ㄐㄧㄣ ㄐㄧㄣ ㄧㄡˇ ㄨㄟˋ", example: "他津津有味地讀著故事書。" },
  { full: "盡善盡美", blank: "盡善盡＿", answer: "美", hint: "美好", meaning: "形容極其完善美好。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄣˋ ㄕㄢˋ ㄐㄧㄣˋ ㄇㄟˇ", example: "這份作品雖不盡善盡美，但很用心。" },
  { full: "進退兩難", blank: "進退兩＿", answer: "難", hint: "困難", meaning: "前進或後退都很困難。", level: "中等", category: "生活常用", zhuyin: "ㄐㄧㄣˋ ㄊㄨㄟˋ ㄌㄧㄤˇ ㄋㄢˊ", example: "這個選擇讓他進退兩難。" },
  { full: "井然有序", blank: "井然有＿", answer: "序", hint: "次序", meaning: "整齊有秩序。", level: "簡單", category: "生活常用", zhuyin: "ㄐㄧㄥˇ ㄖㄢˊ ㄧㄡˇ ㄒㄩˋ", example: "隊伍排得井然有序。" },
  { full: "精益求精", blank: "精益求＿", answer: "精", hint: "更好", meaning: "已經很好還要追求更好。", level: "中等", category: "學習成語", zhuyin: "ㄐㄧㄥ ㄧˋ ㄑㄧㄡˊ ㄐㄧㄥ", example: "做事要精益求精。" }
,
  { full: "百戰百勝", blank: "百戰＿勝", answer: "百", hint: "完整成語中的第 3 個字", meaning: "「百戰百勝」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「百戰百勝」來形容。" },
  { full: "百聞不如一見", blank: "百聞＿如一見", answer: "不", hint: "完整成語中的第 3 個字", meaning: "「百聞不如一見」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「百聞不如一見」來形容。" },
  { full: "百尺竿頭", blank: "百尺＿頭", answer: "竿", hint: "完整成語中的第 3 個字", meaning: "「百尺竿頭」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「百尺竿頭」來形容。" },
  { full: "百家爭鳴", blank: "百家＿鳴", answer: "爭", hint: "完整成語中的第 3 個字", meaning: "「百家爭鳴」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「百家爭鳴」來形容。" },
  { full: "百依百順", blank: "百依＿順", answer: "百", hint: "完整成語中的第 3 個字", meaning: "「百依百順」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「百依百順」來形容。" },
  { full: "百思不解", blank: "百思＿解", answer: "不", hint: "完整成語中的第 3 個字", meaning: "「百思不解」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「百思不解」來形容。" },
  { full: "百年樹人", blank: "百年＿人", answer: "樹", hint: "完整成語中的第 3 個字", meaning: "「百年樹人」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「百年樹人」來形容。" },
  { full: "半推半就", blank: "半推＿就", answer: "半", hint: "完整成語中的第 3 個字", meaning: "「半推半就」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「半推半就」來形容。" },
  { full: "半斤八兩", blank: "半斤＿兩", answer: "八", hint: "完整成語中的第 3 個字", meaning: "「半斤八兩」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「半斤八兩」來形容。" },
  { full: "半夜三更", blank: "半夜＿更", answer: "三", hint: "完整成語中的第 3 個字", meaning: "「半夜三更」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「半夜三更」來形容。" },
  { full: "飽經風霜", blank: "飽經＿霜", answer: "風", hint: "完整成語中的第 3 個字", meaning: "「飽經風霜」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「飽經風霜」來形容。" },
  { full: "暴跳如雷", blank: "暴跳＿雷", answer: "如", hint: "完整成語中的第 3 個字", meaning: "「暴跳如雷」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「暴跳如雷」來形容。" },
  { full: "杯水車薪", blank: "杯水＿薪", answer: "車", hint: "完整成語中的第 3 個字", meaning: "「杯水車薪」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「杯水車薪」來形容。" },
  { full: "背水一戰", blank: "背水＿戰", answer: "一", hint: "完整成語中的第 3 個字", meaning: "「背水一戰」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「背水一戰」來形容。" },
  { full: "閉月羞花", blank: "閉月＿花", answer: "羞", hint: "完整成語中的第 3 個字", meaning: "「閉月羞花」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「閉月羞花」來形容。" },
  { full: "避重就輕", blank: "避重＿輕", answer: "就", hint: "完整成語中的第 3 個字", meaning: "「避重就輕」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「避重就輕」來形容。" },
  { full: "鞭長莫及", blank: "鞭長＿及", answer: "莫", hint: "完整成語中的第 3 個字", meaning: "「鞭長莫及」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「鞭長莫及」來形容。" },
  { full: "別具一格", blank: "別具＿格", answer: "一", hint: "完整成語中的第 3 個字", meaning: "「別具一格」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「別具一格」來形容。" },
  { full: "別開生面", blank: "別開＿面", answer: "生", hint: "完整成語中的第 3 個字", meaning: "「別開生面」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「別開生面」來形容。" },
  { full: "兵不厭詐", blank: "兵不＿詐", answer: "厭", hint: "完整成語中的第 3 個字", meaning: "「兵不厭詐」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「兵不厭詐」來形容。" },
  { full: "兵荒馬亂", blank: "兵荒＿亂", answer: "馬", hint: "完整成語中的第 3 個字", meaning: "「兵荒馬亂」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「兵荒馬亂」來形容。" },
  { full: "並駕齊驅", blank: "並駕＿驅", answer: "齊", hint: "完整成語中的第 3 個字", meaning: "「並駕齊驅」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「並駕齊驅」來形容。" },
  { full: "博古通今", blank: "博古＿今", answer: "通", hint: "完整成語中的第 3 個字", meaning: "「博古通今」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「博古通今」來形容。" },
  { full: "博聞強記", blank: "博聞＿記", answer: "強", hint: "完整成語中的第 3 個字", meaning: "「博聞強記」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「博聞強記」來形容。" },
  { full: "不寒而慄", blank: "不寒＿慄", answer: "而", hint: "完整成語中的第 3 個字", meaning: "「不寒而慄」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「不寒而慄」來形容。" },
  { full: "不謀而合", blank: "不謀＿合", answer: "而", hint: "完整成語中的第 3 個字", meaning: "「不謀而合」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「不謀而合」來形容。" },
  { full: "不約而同", blank: "不約＿同", answer: "而", hint: "完整成語中的第 3 個字", meaning: "「不約而同」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「不約而同」來形容。" },
  { full: "不知所措", blank: "不知＿措", answer: "所", hint: "完整成語中的第 3 個字", meaning: "「不知所措」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「不知所措」來形容。" },
  { full: "才疏學淺", blank: "才疏＿淺", answer: "學", hint: "完整成語中的第 3 個字", meaning: "「才疏學淺」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「才疏學淺」來形容。" },
  { full: "滄海一粟", blank: "滄海＿粟", answer: "一", hint: "完整成語中的第 3 個字", meaning: "「滄海一粟」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「滄海一粟」來形容。" },
  { full: "藏龍臥虎", blank: "藏龍＿虎", answer: "臥", hint: "完整成語中的第 3 個字", meaning: "「藏龍臥虎」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「藏龍臥虎」來形容。" },
  { full: "草菅人命", blank: "草菅＿命", answer: "人", hint: "完整成語中的第 3 個字", meaning: "「草菅人命」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「草菅人命」來形容。" },
  { full: "差強人意", blank: "差強＿意", answer: "人", hint: "完整成語中的第 3 個字", meaning: "「差強人意」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「差強人意」來形容。" },
  { full: "長袖善舞", blank: "長袖＿舞", answer: "善", hint: "完整成語中的第 3 個字", meaning: "「長袖善舞」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「長袖善舞」來形容。" },
  { full: "成竹在胸", blank: "成竹＿胸", answer: "在", hint: "完整成語中的第 3 個字", meaning: "「成竹在胸」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「成竹在胸」來形容。" },
  { full: "出奇制勝", blank: "出奇＿勝", answer: "制", hint: "完整成語中的第 3 個字", meaning: "「出奇制勝」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「出奇制勝」來形容。" },
  { full: "出類拔萃", blank: "出類＿萃", answer: "拔", hint: "完整成語中的第 3 個字", meaning: "「出類拔萃」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「出類拔萃」來形容。" },
  { full: "出人頭地", blank: "出人＿地", answer: "頭", hint: "完整成語中的第 3 個字", meaning: "「出人頭地」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「出人頭地」來形容。" },
  { full: "出神入化", blank: "出神＿化", answer: "入", hint: "完整成語中的第 3 個字", meaning: "「出神入化」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「出神入化」來形容。" },
  { full: "春風化雨", blank: "春風＿雨", answer: "化", hint: "完整成語中的第 3 個字", meaning: "「春風化雨」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「春風化雨」來形容。" },
  { full: "唇亡齒寒", blank: "唇亡＿寒", answer: "齒", hint: "完整成語中的第 3 個字", meaning: "「唇亡齒寒」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「唇亡齒寒」來形容。" },
  { full: "寸步難行", blank: "寸步＿行", answer: "難", hint: "完整成語中的第 3 個字", meaning: "「寸步難行」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「寸步難行」來形容。" },
  { full: "寸草不生", blank: "寸草＿生", answer: "不", hint: "完整成語中的第 3 個字", meaning: "「寸草不生」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「寸草不生」來形容。" },
  { full: "大快人心", blank: "大快＿心", answer: "人", hint: "完整成語中的第 3 個字", meaning: "「大快人心」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「大快人心」來形容。" },
  { full: "大顯身手", blank: "大顯＿手", answer: "身", hint: "完整成語中的第 3 個字", meaning: "「大顯身手」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「大顯身手」來形容。" },
  { full: "膽大心細", blank: "膽大＿細", answer: "心", hint: "完整成語中的第 3 個字", meaning: "「膽大心細」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「膽大心細」來形容。" },
  { full: "當機立斷", blank: "當機＿斷", answer: "立", hint: "完整成語中的第 3 個字", meaning: "「當機立斷」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「當機立斷」來形容。" },
  { full: "刀山火海", blank: "刀山＿海", answer: "火", hint: "完整成語中的第 3 個字", meaning: "「刀山火海」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「刀山火海」來形容。" },
  { full: "得不償失", blank: "得不＿失", answer: "償", hint: "完整成語中的第 3 個字", meaning: "「得不償失」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「得不償失」來形容。" },
  { full: "得心應手", blank: "得心＿手", answer: "應", hint: "完整成語中的第 3 個字", meaning: "「得心應手」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「得心應手」來形容。" },
  { full: "德高望重", blank: "德高＿重", answer: "望", hint: "完整成語中的第 3 個字", meaning: "「德高望重」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「德高望重」來形容。" },
  { full: "顛倒黑白", blank: "顛倒＿白", answer: "黑", hint: "完整成語中的第 3 個字", meaning: "「顛倒黑白」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「顛倒黑白」來形容。" },
  { full: "點石成金", blank: "點石＿金", answer: "成", hint: "完整成語中的第 3 個字", meaning: "「點石成金」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「點石成金」來形容。" },
  { full: "東奔西跑", blank: "東奔＿跑", answer: "西", hint: "完整成語中的第 3 個字", meaning: "「東奔西跑」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「東奔西跑」來形容。" },
  { full: "東山再起", blank: "東山＿起", answer: "再", hint: "完整成語中的第 3 個字", meaning: "「東山再起」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「東山再起」來形容。" },
  { full: "獨具匠心", blank: "獨具＿心", answer: "匠", hint: "完整成語中的第 3 個字", meaning: "「獨具匠心」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「獨具匠心」來形容。" },
  { full: "獨善其身", blank: "獨善＿身", answer: "其", hint: "完整成語中的第 3 個字", meaning: "「獨善其身」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「獨善其身」來形容。" },
  { full: "多此一舉", blank: "多此＿舉", answer: "一", hint: "完整成語中的第 3 個字", meaning: "「多此一舉」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「多此一舉」來形容。" },
  { full: "多多益善", blank: "多多＿善", answer: "益", hint: "完整成語中的第 3 個字", meaning: "「多多益善」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「多多益善」來形容。" },
  { full: "咄咄逼人", blank: "咄咄＿人", answer: "逼", hint: "完整成語中的第 3 個字", meaning: "「咄咄逼人」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「咄咄逼人」來形容。" },
  { full: "耳熟能詳", blank: "耳熟＿詳", answer: "能", hint: "完整成語中的第 3 個字", meaning: "「耳熟能詳」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「耳熟能詳」來形容。" },
  { full: "飛黃騰達", blank: "飛黃＿達", answer: "騰", hint: "完整成語中的第 3 個字", meaning: "「飛黃騰達」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「飛黃騰達」來形容。" },
  { full: "奮不顧身", blank: "奮不＿身", answer: "顧", hint: "完整成語中的第 3 個字", meaning: "「奮不顧身」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「奮不顧身」來形容。" },
  { full: "奮發向上", blank: "奮發＿上", answer: "向", hint: "完整成語中的第 3 個字", meaning: "「奮發向上」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「奮發向上」來形容。" },
  { full: "風雨同舟", blank: "風雨＿舟", answer: "同", hint: "完整成語中的第 3 個字", meaning: "「風雨同舟」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「風雨同舟」來形容。" },
  { full: "逢凶化吉", blank: "逢凶＿吉", answer: "化", hint: "完整成語中的第 3 個字", meaning: "「逢凶化吉」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「逢凶化吉」來形容。" },
  { full: "鳳毛麟角", blank: "鳳毛＿角", answer: "麟", hint: "完整成語中的第 3 個字", meaning: "「鳳毛麟角」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「鳳毛麟角」來形容。" },
  { full: "赴湯蹈火", blank: "赴湯＿火", answer: "蹈", hint: "完整成語中的第 3 個字", meaning: "「赴湯蹈火」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「赴湯蹈火」來形容。" },
  { full: "改邪歸正", blank: "改邪＿正", answer: "歸", hint: "完整成語中的第 3 個字", meaning: "「改邪歸正」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「改邪歸正」來形容。" },
  { full: "甘拜下風", blank: "甘拜＿風", answer: "下", hint: "完整成語中的第 3 個字", meaning: "「甘拜下風」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「甘拜下風」來形容。" },
  { full: "高瞻遠矚", blank: "高瞻＿矚", answer: "遠", hint: "完整成語中的第 3 個字", meaning: "「高瞻遠矚」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「高瞻遠矚」來形容。" },
  { full: "各得其所", blank: "各得＿所", answer: "其", hint: "完整成語中的第 3 個字", meaning: "「各得其所」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「各得其所」來形容。" },
  { full: "各有千秋", blank: "各有＿秋", answer: "千", hint: "完整成語中的第 3 個字", meaning: "「各有千秋」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「各有千秋」來形容。" },
  { full: "功敗垂成", blank: "功敗＿成", answer: "垂", hint: "完整成語中的第 3 個字", meaning: "「功敗垂成」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「功敗垂成」來形容。" },
  { full: "孤注一擲", blank: "孤注＿擲", answer: "一", hint: "完整成語中的第 3 個字", meaning: "「孤注一擲」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「孤注一擲」來形容。" },
  { full: "古色古香", blank: "古色＿香", answer: "古", hint: "完整成語中的第 3 個字", meaning: "「古色古香」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「古色古香」來形容。" },
  { full: "鼓足勇氣", blank: "鼓足＿氣", answer: "勇", hint: "完整成語中的第 3 個字", meaning: "「鼓足勇氣」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「鼓足勇氣」來形容。" },
  { full: "鬼斧神工", blank: "鬼斧＿工", answer: "神", hint: "完整成語中的第 3 個字", meaning: "「鬼斧神工」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「鬼斧神工」來形容。" },
  { full: "海誓山盟", blank: "海誓＿盟", answer: "山", hint: "完整成語中的第 3 個字", meaning: "「海誓山盟」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「海誓山盟」來形容。" },
  { full: "害群之馬", blank: "害群＿馬", answer: "之", hint: "完整成語中的第 3 個字", meaning: "「害群之馬」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「害群之馬」來形容。" },
  { full: "含辛茹苦", blank: "含辛＿苦", answer: "茹", hint: "完整成語中的第 3 個字", meaning: "「含辛茹苦」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「含辛茹苦」來形容。" },
  { full: "汗流浹背", blank: "汗流＿背", answer: "浹", hint: "完整成語中的第 3 個字", meaning: "「汗流浹背」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「汗流浹背」來形容。" },
  { full: "橫衝直撞", blank: "橫衝＿撞", answer: "直", hint: "完整成語中的第 3 個字", meaning: "「橫衝直撞」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「橫衝直撞」來形容。" },
  { full: "胡思亂想", blank: "胡思＿想", answer: "亂", hint: "完整成語中的第 3 個字", meaning: "「胡思亂想」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「胡思亂想」來形容。" },
  { full: "花言巧語", blank: "花言＿語", answer: "巧", hint: "完整成語中的第 3 個字", meaning: "「花言巧語」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「花言巧語」來形容。" },
  { full: "畫龍點睛", blank: "畫龍＿睛", answer: "點", hint: "完整成語中的第 3 個字", meaning: "「畫龍點睛」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「畫龍點睛」來形容。" },
  { full: "歡天喜地", blank: "歡天＿地", answer: "喜", hint: "完整成語中的第 3 個字", meaning: "「歡天喜地」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「歡天喜地」來形容。" },
  { full: "患得患失", blank: "患得＿失", answer: "患", hint: "完整成語中的第 3 個字", meaning: "「患得患失」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「患得患失」來形容。" },
  { full: "回頭是岸", blank: "回頭＿岸", answer: "是", hint: "完整成語中的第 3 個字", meaning: "「回頭是岸」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「回頭是岸」來形容。" },
  { full: "魂不守舍", blank: "魂不＿舍", answer: "守", hint: "完整成語中的第 3 個字", meaning: "「魂不守舍」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「魂不守舍」來形容。" },
  { full: "火上加油", blank: "火上＿油", answer: "加", hint: "完整成語中的第 3 個字", meaning: "「火上加油」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「火上加油」來形容。" },
  { full: "禍不單行", blank: "禍不＿行", answer: "單", hint: "完整成語中的第 3 個字", meaning: "「禍不單行」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「禍不單行」來形容。" },
  { full: "急公好義", blank: "急公＿義", answer: "好", hint: "完整成語中的第 3 個字", meaning: "「急公好義」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「急公好義」來形容。" },
  { full: "疾風勁草", blank: "疾風＿草", answer: "勁", hint: "完整成語中的第 3 個字", meaning: "「疾風勁草」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「疾風勁草」來形容。" },
  { full: "家常便飯", blank: "家常＿飯", answer: "便", hint: "完整成語中的第 3 個字", meaning: "「家常便飯」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「家常便飯」來形容。" },
  { full: "價廉物美", blank: "價廉＿美", answer: "物", hint: "完整成語中的第 3 個字", meaning: "「價廉物美」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「價廉物美」來形容。" },
  { full: "將心比心", blank: "將心＿心", answer: "比", hint: "完整成語中的第 3 個字", meaning: "「將心比心」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「將心比心」來形容。" },
  { full: "嬌生慣養", blank: "嬌生＿養", answer: "慣", hint: "完整成語中的第 3 個字", meaning: "「嬌生慣養」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「嬌生慣養」來形容。" },
  { full: "接二連三", blank: "接二＿三", answer: "連", hint: "完整成語中的第 3 個字", meaning: "「接二連三」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「接二連三」來形容。" },
  { full: "借題發揮", blank: "借題＿揮", answer: "發", hint: "完整成語中的第 3 個字", meaning: "「借題發揮」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「借題發揮」來形容。" },
  { full: "金玉良言", blank: "金玉＿言", answer: "良", hint: "完整成語中的第 3 個字", meaning: "「金玉良言」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「金玉良言」來形容。" },
  { full: "盡力而為", blank: "盡力＿為", answer: "而", hint: "完整成語中的第 3 個字", meaning: "「盡力而為」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「盡力而為」來形容。" },
  { full: "驚天動地", blank: "驚天＿地", answer: "動", hint: "完整成語中的第 3 個字", meaning: "「驚天動地」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「驚天動地」來形容。" },
  { full: "居安思危", blank: "居安＿危", answer: "思", hint: "完整成語中的第 3 個字", meaning: "「居安思危」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「居安思危」來形容。" },
  { full: "舉世聞名", blank: "舉世＿名", answer: "聞", hint: "完整成語中的第 3 個字", meaning: "「舉世聞名」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「舉世聞名」來形容。" },
  { full: "開門見山", blank: "開門＿山", answer: "見", hint: "完整成語中的第 3 個字", meaning: "「開門見山」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「開門見山」來形容。" },
  { full: "刻不容緩", blank: "刻不＿緩", answer: "容", hint: "完整成語中的第 3 個字", meaning: "「刻不容緩」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「刻不容緩」來形容。" },
  { full: "刻骨銘心", blank: "刻骨＿心", answer: "銘", hint: "完整成語中的第 3 個字", meaning: "「刻骨銘心」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「刻骨銘心」來形容。" },
  { full: "苦口婆心", blank: "苦口＿心", answer: "婆", hint: "完整成語中的第 3 個字", meaning: "「苦口婆心」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「苦口婆心」來形容。" },
  { full: "誇誇其談", blank: "誇誇＿談", answer: "其", hint: "完整成語中的第 3 個字", meaning: "「誇誇其談」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「誇誇其談」來形容。" },
  { full: "膾炙人口", blank: "膾炙＿口", answer: "人", hint: "完整成語中的第 3 個字", meaning: "「膾炙人口」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「膾炙人口」來形容。" },
  { full: "牢不可破", blank: "牢不＿破", answer: "可", hint: "完整成語中的第 3 個字", meaning: "「牢不可破」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「牢不可破」來形容。" },
  { full: "老馬識途", blank: "老馬＿途", answer: "識", hint: "完整成語中的第 3 個字", meaning: "「老馬識途」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「老馬識途」來形容。" },
  { full: "冷言冷語", blank: "冷言＿語", answer: "冷", hint: "完整成語中的第 3 個字", meaning: "「冷言冷語」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「冷言冷語」來形容。" },
  { full: "理直氣壯", blank: "理直＿壯", answer: "氣", hint: "完整成語中的第 3 個字", meaning: "「理直氣壯」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「理直氣壯」來形容。" },
  { full: "力不從心", blank: "力不＿心", answer: "從", hint: "完整成語中的第 3 個字", meaning: "「力不從心」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「力不從心」來形容。" },
  { full: "歷歷在目", blank: "歷歷＿目", answer: "在", hint: "完整成語中的第 3 個字", meaning: "「歷歷在目」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「歷歷在目」來形容。" },
  { full: "立竿見影", blank: "立竿＿影", answer: "見", hint: "完整成語中的第 3 個字", meaning: "「立竿見影」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「立竿見影」來形容。" },
  { full: "兩全其美", blank: "兩全＿美", answer: "其", hint: "完整成語中的第 3 個字", meaning: "「兩全其美」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「兩全其美」來形容。" },
  { full: "量力而為", blank: "量力＿為", answer: "而", hint: "完整成語中的第 3 個字", meaning: "「量力而為」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「量力而為」來形容。" },
  { full: "了如指掌", blank: "了如＿掌", answer: "指", hint: "完整成語中的第 3 個字", meaning: "「了如指掌」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「了如指掌」來形容。" },
  { full: "臨危不亂", blank: "臨危＿亂", answer: "不", hint: "完整成語中的第 3 個字", meaning: "「臨危不亂」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「臨危不亂」來形容。" },
  { full: "玲瓏剔透", blank: "玲瓏＿透", answer: "剔", hint: "完整成語中的第 3 個字", meaning: "「玲瓏剔透」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「玲瓏剔透」來形容。" },
  { full: "流連忘返", blank: "流連＿返", answer: "忘", hint: "完整成語中的第 3 個字", meaning: "「流連忘返」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「流連忘返」來形容。" },
  { full: "龍潭虎穴", blank: "龍潭＿穴", answer: "虎", hint: "完整成語中的第 3 個字", meaning: "「龍潭虎穴」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「龍潭虎穴」來形容。" },
  { full: "廬山真面目", blank: "廬山＿面目", answer: "真", hint: "完整成語中的第 3 個字", meaning: "「廬山真面目」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「廬山真面目」來形容。" },
  { full: "馬馬虎虎", blank: "馬馬＿虎", answer: "虎", hint: "完整成語中的第 3 個字", meaning: "「馬馬虎虎」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「馬馬虎虎」來形容。" },
  { full: "滿腹經綸", blank: "滿腹＿綸", answer: "經", hint: "完整成語中的第 3 個字", meaning: "「滿腹經綸」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「滿腹經綸」來形容。" },
  { full: "美中不足", blank: "美中＿足", answer: "不", hint: "完整成語中的第 3 個字", meaning: "「美中不足」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「美中不足」來形容。" },
  { full: "夢寐以求", blank: "夢寐＿求", answer: "以", hint: "完整成語中的第 3 個字", meaning: "「夢寐以求」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「夢寐以求」來形容。" },
  { full: "明察秋毫", blank: "明察＿毫", answer: "秋", hint: "完整成語中的第 3 個字", meaning: "「明察秋毫」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「明察秋毫」來形容。" },
  { full: "明辨是非", blank: "明辨＿非", answer: "是", hint: "完整成語中的第 3 個字", meaning: "「明辨是非」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「明辨是非」來形容。" },
  { full: "名副其實", blank: "名副＿實", answer: "其", hint: "完整成語中的第 3 個字", meaning: "「名副其實」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「名副其實」來形容。" },
  { full: "莫名其妙", blank: "莫名＿妙", answer: "其", hint: "完整成語中的第 3 個字", meaning: "「莫名其妙」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「莫名其妙」來形容。" },
  { full: "目不轉睛", blank: "目不＿睛", answer: "轉", hint: "完整成語中的第 3 個字", meaning: "「目不轉睛」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「目不轉睛」來形容。" },
  { full: "目中無人", blank: "目中＿人", answer: "無", hint: "完整成語中的第 3 個字", meaning: "「目中無人」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「目中無人」來形容。" },
  { full: "難能可貴", blank: "難能＿貴", answer: "可", hint: "完整成語中的第 3 個字", meaning: "「難能可貴」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「難能可貴」來形容。" },
  { full: "囊螢映雪", blank: "囊螢＿雪", answer: "映", hint: "完整成語中的第 3 個字", meaning: "「囊螢映雪」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「囊螢映雪」來形容。" },
  { full: "逆水行舟", blank: "逆水＿舟", answer: "行", hint: "完整成語中的第 3 個字", meaning: "「逆水行舟」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「逆水行舟」來形容。" },
  { full: "念念不忘", blank: "念念＿忘", answer: "不", hint: "完整成語中的第 3 個字", meaning: "「念念不忘」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「念念不忘」來形容。" },
  { full: "寧缺勿濫", blank: "寧缺＿濫", answer: "勿", hint: "完整成語中的第 3 個字", meaning: "「寧缺勿濫」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「寧缺勿濫」來形容。" },
  { full: "怒髮衝冠", blank: "怒髮＿冠", answer: "衝", hint: "完整成語中的第 3 個字", meaning: "「怒髮衝冠」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「怒髮衝冠」來形容。" },
  { full: "排山倒海", blank: "排山＿海", answer: "倒", hint: "完整成語中的第 3 個字", meaning: "「排山倒海」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「排山倒海」來形容。" },
  { full: "旁敲側擊", blank: "旁敲＿擊", answer: "側", hint: "完整成語中的第 3 個字", meaning: "「旁敲側擊」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「旁敲側擊」來形容。" },
  { full: "拋磚引玉", blank: "拋磚＿玉", answer: "引", hint: "完整成語中的第 3 個字", meaning: "「拋磚引玉」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「拋磚引玉」來形容。" },
  { full: "破鏡重圓", blank: "破鏡＿圓", answer: "重", hint: "完整成語中的第 3 個字", meaning: "「破鏡重圓」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「破鏡重圓」來形容。" },
  { full: "齊心協力", blank: "齊心＿力", answer: "協", hint: "完整成語中的第 3 個字", meaning: "「齊心協力」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「齊心協力」來形容。" },
  { full: "騎虎難下", blank: "騎虎＿下", answer: "難", hint: "完整成語中的第 3 個字", meaning: "「騎虎難下」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「騎虎難下」來形容。" },
  { full: "千里迢迢", blank: "千里＿迢", answer: "迢", hint: "完整成語中的第 3 個字", meaning: "「千里迢迢」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「千里迢迢」來形容。" },
  { full: "千篇一律", blank: "千篇＿律", answer: "一", hint: "完整成語中的第 3 個字", meaning: "「千篇一律」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「千篇一律」來形容。" },
  { full: "前所未有", blank: "前所＿有", answer: "未", hint: "完整成語中的第 3 個字", meaning: "「前所未有」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「前所未有」來形容。" },
  { full: "淺嘗輒止", blank: "淺嘗＿止", answer: "輒", hint: "完整成語中的第 3 個字", meaning: "「淺嘗輒止」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「淺嘗輒止」來形容。" },
  { full: "強詞奪理", blank: "強詞＿理", answer: "奪", hint: "完整成語中的第 3 個字", meaning: "「強詞奪理」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「強詞奪理」來形容。" },
  { full: "巧奪天工", blank: "巧奪＿工", answer: "天", hint: "完整成語中的第 3 個字", meaning: "「巧奪天工」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「巧奪天工」來形容。" },
  { full: "切磋琢磨", blank: "切磋＿磨", answer: "琢", hint: "完整成語中的第 3 個字", meaning: "「切磋琢磨」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「切磋琢磨」來形容。" },
  { full: "青出於藍", blank: "青出＿藍", answer: "於", hint: "完整成語中的第 3 個字", meaning: "「青出於藍」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「青出於藍」來形容。" },
  { full: "輕而易舉", blank: "輕而＿舉", answer: "易", hint: "完整成語中的第 3 個字", meaning: "「輕而易舉」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「輕而易舉」來形容。" },
  { full: "傾盆大雨", blank: "傾盆＿雨", answer: "大", hint: "完整成語中的第 3 個字", meaning: "「傾盆大雨」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「傾盆大雨」來形容。" },
  { full: "情同手足", blank: "情同＿足", answer: "手", hint: "完整成語中的第 3 個字", meaning: "「情同手足」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「情同手足」來形容。" },
  { full: "窮途末路", blank: "窮途＿路", answer: "末", hint: "完整成語中的第 3 個字", meaning: "「窮途末路」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「窮途末路」來形容。" },
  { full: "取長補短", blank: "取長＿短", answer: "補", hint: "完整成語中的第 3 個字", meaning: "「取長補短」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「取長補短」來形容。" },
  { full: "全力以赴", blank: "全力＿赴", answer: "以", hint: "完整成語中的第 3 個字", meaning: "「全力以赴」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「全力以赴」來形容。" },
  { full: "群策群力", blank: "群策＿力", answer: "群", hint: "完整成語中的第 3 個字", meaning: "「群策群力」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「群策群力」來形容。" },
  { full: "人云亦云", blank: "人云＿云", answer: "亦", hint: "完整成語中的第 3 個字", meaning: "「人云亦云」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「人云亦云」來形容。" },
  { full: "任勞任怨", blank: "任勞＿怨", answer: "任", hint: "完整成語中的第 3 個字", meaning: "「任勞任怨」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「任勞任怨」來形容。" },
  { full: "如火如荼", blank: "如火＿荼", answer: "如", hint: "完整成語中的第 3 個字", meaning: "「如火如荼」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「如火如荼」來形容。" },
  { full: "若無其事", blank: "若無＿事", answer: "其", hint: "完整成語中的第 3 個字", meaning: "「若無其事」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「若無其事」來形容。" },
  { full: "三顧茅廬", blank: "三顧＿廬", answer: "茅", hint: "完整成語中的第 3 個字", meaning: "「三顧茅廬」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「三顧茅廬」來形容。" },
  { full: "三思而行", blank: "三思＿行", answer: "而", hint: "完整成語中的第 3 個字", meaning: "「三思而行」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「三思而行」來形容。" },
  { full: "善罷甘休", blank: "善罷＿休", answer: "甘", hint: "完整成語中的第 3 個字", meaning: "「善罷甘休」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「善罷甘休」來形容。" },
  { full: "賞心悅目", blank: "賞心＿目", answer: "悅", hint: "完整成語中的第 3 個字", meaning: "「賞心悅目」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「賞心悅目」來形容。" },
  { full: "深謀遠慮", blank: "深謀＿慮", answer: "遠", hint: "完整成語中的第 3 個字", meaning: "「深謀遠慮」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「深謀遠慮」來形容。" },
  { full: "神機妙算", blank: "神機＿算", answer: "妙", hint: "完整成語中的第 3 個字", meaning: "「神機妙算」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「神機妙算」來形容。" },
  { full: "生龍活虎", blank: "生龍＿虎", answer: "活", hint: "完整成語中的第 3 個字", meaning: "「生龍活虎」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「生龍活虎」來形容。" },
  { full: "生氣勃勃", blank: "生氣＿勃", answer: "勃", hint: "完整成語中的第 3 個字", meaning: "「生氣勃勃」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「生氣勃勃」來形容。" },
  { full: "失而復得", blank: "失而＿得", answer: "復", hint: "完整成語中的第 3 個字", meaning: "「失而復得」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「失而復得」來形容。" },
  { full: "實事求是", blank: "實事＿是", answer: "求", hint: "完整成語中的第 3 個字", meaning: "「實事求是」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「實事求是」來形容。" },
  { full: "始終如一", blank: "始終＿一", answer: "如", hint: "完整成語中的第 3 個字", meaning: "「始終如一」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「始終如一」來形容。" },
  { full: "世外桃源", blank: "世外＿源", answer: "桃", hint: "完整成語中的第 3 個字", meaning: "「世外桃源」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「世外桃源」來形容。" },
  { full: "事與願違", blank: "事與＿違", answer: "願", hint: "完整成語中的第 3 個字", meaning: "「事與願違」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「事與願違」來形容。" },
  { full: "視而不見", blank: "視而＿見", answer: "不", hint: "完整成語中的第 3 個字", meaning: "「視而不見」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「視而不見」來形容。" },
  { full: "手不釋卷", blank: "手不＿卷", answer: "釋", hint: "完整成語中的第 3 個字", meaning: "「手不釋卷」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「手不釋卷」來形容。" },
  { full: "守口如瓶", blank: "守口＿瓶", answer: "如", hint: "完整成語中的第 3 個字", meaning: "「守口如瓶」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "人物行為", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「守口如瓶」來形容。" },
  { full: "水到渠成", blank: "水到＿成", answer: "渠", hint: "完整成語中的第 3 個字", meaning: "「水到渠成」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "數字成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「水到渠成」來形容。" },
  { full: "水深火熱", blank: "水深＿熱", answer: "火", hint: "完整成語中的第 3 個字", meaning: "「水深火熱」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "生活常用", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「水深火熱」來形容。" },
  { full: "順水推舟", blank: "順水＿舟", answer: "推", hint: "完整成語中的第 3 個字", meaning: "「順水推舟」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "中等", category: "學習成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「順水推舟」來形容。" },
  { full: "死灰復燃", blank: "死灰＿燃", answer: "復", hint: "完整成語中的第 3 個字", meaning: "「死灰復燃」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "品德修養", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「死灰復燃」來形容。" },
  { full: "談笑風生", blank: "談笑＿生", answer: "風", hint: "完整成語中的第 3 個字", meaning: "「談笑風生」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "故事寓言", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「談笑風生」來形容。" },
  { full: "探囊取物", blank: "探囊＿物", answer: "取", hint: "完整成語中的第 3 個字", meaning: "「探囊取物」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "困難", category: "歷史故事", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「探囊取物」來形容。" },
  { full: "提心吊膽", blank: "提心＿膽", answer: "吊", hint: "完整成語中的第 3 個字", meaning: "「提心吊膽」是常見成語，可用來描述生活、學習或處事中的相關情境。", level: "簡單", category: "自然成語", zhuyin: "ㄓㄨˋ ㄧㄣ ㄉㄞˋ ㄐㄧㄠˋ", example: "這個情況可以用「提心吊膽」來形容。" }
];
